In [18]:
import pandas as pd
import os

In [12]:
df2000 = pd.read_csv("dataholder_2000.csv", index_col=0)

In [8]:
df2001 = pd.read_csv("dataholder_2001.csv", index_col=0)

In [17]:
df2000.append(df2001, ignore_index=True)

,0,1,2,3,4,5,6,7,8,9,...,sma_20,sma_25,sma_30,ulos_7_14_28,ulos_8_16_32,ulos_9_18_36,volume,wR_14,wR_18,wR_22
0,1.028144,1.170187,1.286510,-1.543310,-1.484914,-1.437555,-1.691508,-1.800549,-1.458727,-2.051432,...,147.4835,145.8020,144.297000,52.212262,52.341188,50.377367,6378500.0,-36.699164,-26.764855,-25.434363
1,0.782266,0.635844,0.613666,-1.253851,-1.205585,-1.163817,-1.618313,-1.628850,-1.533933,-1.381810,...,23.3575,22.7516,22.375667,58.605751,59.478761,56.570493,278700.0,-35.555556,-19.928826,-18.211382
2,0.599222,0.610523,0.661145,-2.264798,-2.110202,-1.987110,-3.538897,-3.313057,-3.684985,-2.684662,...,26.4325,26.2616,25.990333,51.517043,50.994433,52.541772,129200.0,-13.306452,-11.301370,-10.248447
3,1.846375,1.992617,2.047292,-2.449167,-2.310358,-2.199706,-2.012927,-2.519905,-1.773981,-0.076036,...,28.3960,28.2516,27.898000,54.418489,54.073401,55.082486,38000.0,-21.563981,-21.563981,-21.563981
4,0.093797,0.027102,0.013521,-0.767391,-0.698835,-0.653558,-1.295427,-1.267933,-1.343644,-0.698595,...,20.9945,20.7108,20.659667,65.118955,65.237850,62.581741,55100.0,-33.090909,-22.750000,-20.728929
5,1.047003,0.730313,0.696770,-1.334016,-1.315698,-1.302768,-1.224061,-1.291203,-1.178658,-2.113532,...,28.0620,27.6068,27.264667,52.937189,51.619489,50.330987,23000.0,-30.327869,-14.889336,-14.889336
6,0.635146,0.534904,0.548933,-1.241507,-1.158673,-1.089709,-1.878080,-1.834100,-1.847686,-1.225900,...,29.8835,29.4972,29.245667,53.712769,55.231303,51.984561,29000.0,-35.567010,-18.062827,-16.586538
7,1.343182,1.085069,0.852864,-1.319639,-1.427601,-1.526051,-0.283821,-0.384598,-0.122748,-1.373285,...,60.0945,59.7480,59.097333,54.926018,54.381483,52.929918,173000.0,-52.279635,-52.279635,-52.279635
8,0.977007,0.661013,0.684910,-0.762045,-0.691705,-0.664530,-1.183201,-1.198431,-1.020849,-1.541536,...,61.3000,61.0800,61.000000,70.812028,70.298174,70.252590,50875.0,-37.037037,-29.411765,-27.027027
9,-0.021189,-0.156267,-0.151025,-1.126849,-1.117679,-1.110172,-1.062632,-1.110811,-1.111733,-1.589321,...,22.3375,21.9372,21.755667,48.293919,46.335628,45.786984,22600.0,-47.583643,-29.290618,-26.446281
10,1.188492,1.178079,1.191843,-1.399414,-1.349357,-1.304862,-1.861153,-1.850785,-1.753853,-0.960408,...,28.1415,27.5408,27.146667,63.563370,63.921691,62.681525,13600.0,-20.588235,-10.177706,-9.375000
11,-0.117745,-0.778175,0.016647,-1.034576,-1.028115,-1.004613,-0.791761,-1.045128,-0.598022,-1.332722,...,19.1595,19.3324,19.139667,42.580749,40.769581,41.028622,13900.0,-58.309038,-58.309038,-63.613232
12,0.901328,0.780557,0.818446,-1.271636,-1.226212,-1.192344,-1.648135,-1.651972,-1.625353,-1.330810,...,107.7255,106.2764,105.349333,59.696785,58.136415,55.359218,2279700.0,-34.556213,-17.505995,-16.685714
13,-0.271606,-0.945940,0.036294,1.179703,1.228410,1.254908,0.512283,0.557300,0.245495,0.886326,...,27.5785,27.8104,27.860667,57.651755,58.534731,56.390881,32700.0,-65.538462,-65.538462,-66.863905
14,-0.952306,-1.001237,-0.863672,0.363119,0.505358,0.841580,-0.331937,-0.607492,-0.189212,1.276306,...,13.5255,13.5700,13.531000,54.432049,52.857221,53.695274,65800.0,-53.703704,-53.703704,-53.703704
15,0.042571,-1.236949,-0.039756,0.123948,0.463377,0.774708,-1.264360,-1.326741,-1.284802,-1.373069,...,18.1095,18.0276,17.940333,48.462437,48.803565,47.722315,14000.0,-43.589744,-37.569061,-33.009709
16,0.824741,0.879041,0.766940,-2.700726,-2.585424,-2.466004,-1.396263,-1.729314,-0.885414,1.069017,...,10.3255,10.3532,10.337667,48.675810,51.069007,49.684914,6000.0,-41.891892,-41.891892,-41.891892
17,1.018300,0.655134,0.726070,-1.555864,-1.509030,-1.468692,-1.370758,-1.568731,-1.053269,-1.817911,...,148.0460,146.2148,144.900667,52.120321,52.436622,52.677649,6023600.0,-30.013928,-21.889284,-21.889284
18,1.115898,0.538302,0.479206,-1.262181,-1.223918,-1.188871,-1.406345,-1.487049,-1.230193,-0.819681,...,23.5550,22.8740,22.515333,56.085110,53.851157,56.401189,636400.0,-51.428571,-28.825623,-26.341463
19,1.816283,1.914977,1.987929,-2.228746,-2.087988,-1.975127,-3.634201,-3.407227,-3.597199,-2.691568,...,26.5400,26.3216,26.133333,49.779155,50.324334,50.811558,169700.0,-16.532258,-14.041096,-13.666667
20,1.935366,2.112064,2.163585,-2.500613,-2.359566,-2.245690,-1.192087,-1.861092,-0.854632,0.897446,...,28.4515,28.3308,28.033000,44.674127,50.670110,51.650902,255400.0,-32.227488,-32.227488,-32.227488
21,-0.482646,-0.649214,-0.725058,-0.867968,-0.804801,-0.761650,-1.356808,-1.331525,-1.390412,-0.903630,...,21.1060,20.7724,20.713333,59.250409,59.672220,62.151019,169700.0,-43.272727,-29.974811,-29.750000
22,0.478125,0.135194,0.376839,-1.383806,-1.363919,-1.348919,-1.168813,-1.272769,-1.071469,0.449457,...,28.2520,27.7364,27.406333,53.409795,54.348447,54.866498,136600.0,-12.295082,-6.036217,-6.036217
23,0.581521,0.324280,0.329872,-1.266407,-1.196119,-1.136042,-1.725769,-1.742269,-1.600208,-1.118821,...,30.0305,29.5824,29.360000,55.639923,53.908600,55.028418,6000.0,-31.443299,-15.968586,-14.663462
24,0.838037,0.721484,0.493483,-1.095309,-1.233822,-1.370803,-0.042751,-0.139070,0.101427,-0.018551,...,60.1350,59.8272,59.273333,59.784635,57.943884,56.342900,233000.0,-37.082067,-37.082067,-37.082067
25,1.415232,1.079010,1.119763,-0.490018,-0.451135,-0.446430,-0.658059,-0.740459,-0.409009,-0.970033,...,61.5000,61.1800,61.150000,70.955783,71.174758,71.259563,39350.0,-33.333333,-26.470588,-24.324324
26,-0.265657,-0.281658,-0.336064,-1.220548,-1.202742,-1.188520,-1.228620,-1.266804,-1.258133,-1.800146,...,22.4625,22.0136,21.816333,41.524425,43.109045,43.498643,43700.0,-61.338290,-37.844037,-35.106383
27,0.123665,-0.243648,-0.236587,-1.420448,-1.375771,-1.335206,-1.734555,-1.782959,-1.536478,-1.562535,...,28.3990,27.7124,27.341333,59.243149,60.408995,61.910223,55700.0,-21.000000,-10.177706,-9.662577
28,0.897582,-0.080108,0.701896,-0.903117,-0.910238,-0.899964,-0.563304,-0.810479,-0.368151,-0.876894,...,19.1035,19.2948,19.179333,49.611512,48.308192,46.295087,27700.0,-38.192420,-38.192420,-46.055980
29,0.531926,0.175845,0.183277,-1.305536,-1.265119,-1.233905,-1.536142,-1.589822,-1.436069,-1.184966,...,108.2930,106.5576,105.761000,56.788978,57.274484,57.227332,1027100.0,-40.833333,-20.563549,-19.600000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7342,0.800462,0.933901,0.925106,0.259808,0.227413,0.194929,0.408553,0.397913,0.428396,0.349164,...,25.5325,25.6152,25.634333,50.702101,50.722855,55.918883,17500.0,-33.333333,-36.000000,-39.393939
7343,0.063613,0.072739,0.078024,0.712502,0.008413,-1.052320,2.122216,2.077161,2.112746,1.064350,...,27.1440,27.0608,26.982000,67.478935,70.873960,70.484645,1280200.0,-3.743316,-3.743316,-3.381643
7344,0.342548,0.505448,0.526752,-0.097554,-0.758724,-1.511782,1.729785,1.605084,1.872699,1.811745,...,26.8975,26.8012,26.712333,49.300846,52.739817,56.767807,28600.0,-13.178295,-37.078652,-30.985915
7345,0.661075,0.849025,0.881641,1.320406,1.137998,0.912988,2.212055,2.111360,2.292743,3.019428,...,24.8195,24.7544,24.702667,32.646981,33.914745,40.221984,3130600.0,-62.631579,-71.020408,-71.020408
7346,0.518647,0.426175,0.517423,0.363582,0.346481,0.319080,0.392094,0.419234,0.405139,2.237641,...,31.9180,32.3088,32.525333,52.187294,53.044393,51.910430,312625.0,-46.428571,-68.750000,-68.750000
7347,0.305813,0.371269,0.403503,0.834688,0.640464,0.418456,1.795755,1.681992,1.930282,1.461925,...,21.8065,21.8584,21.867000,44.118574,50.407840,53.462857,158700.0,-52.380952,-72.375691,-72.375691
7348,0.798120,0.852148,1.047464,1.142609,0.691179,-0.043546,2.303117,2.175466,2.415761,2.371560,...,28.0085,27.8660,27.764333,62.231828,60.448600,63.781175,17700.0,-3.076923,-2.926829,-2.620087
7349,0.592579,0.759673,0.807008,-1.361937,-1.400678,-1.433813,0.106928,0.210131,0.045340,0.496258,...,14.7665,14.5920,14.442333,64.232606,62.687687,63.950132,4700.0,-0.000000,-0.000000,-0.000000
7350,0.161764,0.194439,0.208988,1.341446,0.993579,0.467360,2.383551,2.254589,2.490542,2.198464,...,99.9480,99.7472,99.644000,53.553135,57.688819,60.718895,1375200.0,-17.647059,-17.832957,-16.155419
7351,0.360929,0.502879,0.534826,0.569212,0.177846,-0.352442,1.792403,1.721067,1.865900,2.425959,...,14.6670,14.6188,14.584333,48.526982,46.812005,53.468817,146400.0,-21.250000,-46.153846,-45.762712
7352,0.437145,0.650702,0.606236,0.319832,-0.380191,-1.097650,2.055847,1.947256,2.161902,2.222753,...,9.2345,9.1460,9.110000,41.284281,38.466626,46.372298,24600.0,-54.000000,-61.333333,-38.016529
7353,0.802390,0.885087,0.999034,-0.537960,-1.305676,-1.915561,1.764712,1.619502,1.935656,1.798596,...,10.7780,10.7384,10.699667,53.652490,49.815277,49.741583,3600.0,-56.250000,-61.818182,-61.818182
7354,0.356539,0.426764,0.453271,1.310669,1.165346,1.005081,2.140056,2.039229,2.222874,0.774997,...,9.2740,9.2872,9.302333,56.239515,52.440391,52.037025,7800.0,-9.523810,-17.391304,-19.148936
7355,-0.082371,-0.049012,-0.065996,1.429202,1.243833,1.021423,2.248737,2.178474,2.240324,2.698407,...,114.9540,114.9080,114.911667,39.480782,44.836151,46.901335,14030200.0,-51.578947,-61.666667,-61.666667
7356,0.204301,0.242855,0.254547,1.482180,1.312455,1.107737,2.115131,2.122680,2.000203,2.114784,...,26.1435,26.1680,26.185333,52.511920,57.379474,60.159257,1806500.0,-29.365079,-29.365079,-29.365079
7357,-0.079825,-0.071323,0.494222,0.464743,0.365780,0.278168,1.015676,0.984960,0.993965,1.262532,...,27.6510,27.6600,27.776667,53.845041,60.786154,61.741394,57400.0,-16.265060,-16.265060,-16.265060
7358,1.273684,1.209738,1.426332,-0.820821,-0.692273,-0.574917,-1.547855,-1.458579,-1.613247,-0.097331,...,25.8985,25.8072,25.793000,51.539364,55.564242,56.722464,121000.0,-20.634921,-20.634921,-20.634921
7359,-0.346966,-0.262897,0.096634,0.396890,0.363507,0.330394,0.523337,0.518576,0.533382,0.627548,...,25.5025,25.5860,25.632667,44.865804,47.008516,46.880042,45400.0,-45.833333,-48.000000,-50.757576
7360,-0.447079,-0.514068,-0.561931,0.813797,0.217199,-0.711606,2.055133,2.072770,1.944059,0.709564,...,27.2040,27.0940,27.025000,56.304999,58.735337,64.361513,60600.0,-22.459893,-22.459893,-20.289855
7361,0.148301,0.273220,0.264394,0.356738,-0.196427,-0.902743,1.909056,1.778208,2.055661,1.987412,...,26.9270,26.8252,26.742333,42.650139,42.297514,48.246046,27100.0,-44.000000,-60.674157,-50.704225
7362,-0.378160,-0.374714,-0.441350,1.257318,1.107591,0.920993,2.015318,1.972649,1.995263,1.649852,...,24.7925,24.7388,24.685000,28.244490,29.016209,32.369616,1913000.0,-91.847826,-93.877551,-93.877551
7363,0.308993,0.478109,0.295483,0.530530,0.503342,0.470741,0.649446,0.651633,0.681852,1.486239,...,31.7840,32.1856,32.438667,46.202453,46.071460,48.544727,100675.0,-71.428571,-83.333333,-83.333333
7364,0.018731,0.057098,0.049829,1.012188,0.844356,0.657837,1.915264,1.800478,2.043763,1.539072,...,21.7665,21.8244,21.856000,39.224762,38.200209,45.862959,1594000.0,-78.095238,-87.292818,-87.292818
7365,-0.027063,0.058623,0.060967,1.487035,1.135390,0.578641,2.475807,2.356778,2.549260,1.680780,...,28.0685,27.9120,27.812667,49.131665,52.989913,54.316971,30600.0,-27.500000,-27.500000,-23.913043
7366,-1.018555,-0.723800,-0.819049,-1.500474,-1.513806,-1.527238,-0.297695,-0.196893,-0.366998,0.282078,...,14.8350,14.6568,14.491333,60.666398,60.230937,60.921670,34900.0,-28.260870,-22.807018,-15.028902
7367,-0.251239,-0.292871,-0.333178,1.560896,1.280297,0.874864,2.485246,2.371415,2.540816,2.754597,...,100.0085,99.7432,99.666000,39.155197,47.004908,51.593533,1545800.0,-48.416290,-48.532731,-43.967280
7368,-0.446102,-0.392128,-0.432421,0.753274,0.428296,-0.018013,1.830466,1.776596,1.863585,1.878639,...,14.6965,14.6428,14.614333,54.454600,53.195644,53.773402,38100.0,-0.000000,-20.512821,-20.338983
7369,-0.792699,-1.026160,-1.284462,0.420489,-0.150261,-0.808162,1.928436,1.859656,1.970805,1.512643,...,9.2505,9.1528,9.121000,36.866097,40.987358,40.786379,54200.0,-72.000000,-79.710145,-51.401869
7370,-0.050993,-0.044715,-0.050685,0.072329,-0.590318,-1.274722,1.927549,1.779900,2.101548,1.467032,...,10.7790,10.7392,10.710000,48.334336,50.655984,48.180703,8900.0,-75.000000,-78.181818,-78.181818
7371,0.303355,0.367905,0.381244,1.535850,1.397550,1.253122,2.342122,2.249083,2.374661,1.501274,...,9.2810,9.2916,9.307000,58.302852,56.583785,55.563563,16100.0,-6.666667,-8.695652,-8.695652

In [35]:
df = pd.DataFrame()
for filename in os.listdir():
    if filename.split('.')[-1] == 'csv':
        df = df.append(pd.read_csv(filename, index_col=0))
df.reset_index(inplace=True,drop=True)

In [36]:
df

,0,1,2,3,4,5,6,7,8,9,...,sma_20,sma_25,sma_30,ulos_7_14_28,ulos_8_16_32,ulos_9_18_36,volume,wR_14,wR_18,wR_22
0,1.028144,1.170187,1.286510,-1.543310,-1.484914,-1.437555,-1.691508,-1.800549,-1.458727,-2.051432,...,147.4835,145.8020,144.297000,52.212262,52.341188,50.377367,6378500.0,-36.699164,-26.764855,-25.434363
1,0.782266,0.635844,0.613666,-1.253851,-1.205585,-1.163817,-1.618313,-1.628850,-1.533933,-1.381810,...,23.3575,22.7516,22.375667,58.605751,59.478761,56.570493,278700.0,-35.555556,-19.928826,-18.211382
2,0.599222,0.610523,0.661145,-2.264798,-2.110202,-1.987110,-3.538897,-3.313057,-3.684985,-2.684662,...,26.4325,26.2616,25.990333,51.517043,50.994433,52.541772,129200.0,-13.306452,-11.301370,-10.248447
3,1.846375,1.992617,2.047292,-2.449167,-2.310358,-2.199706,-2.012927,-2.519905,-1.773981,-0.076036,...,28.3960,28.2516,27.898000,54.418489,54.073401,55.082486,38000.0,-21.563981,-21.563981,-21.563981
4,0.093797,0.027102,0.013521,-0.767391,-0.698835,-0.653558,-1.295427,-1.267933,-1.343644,-0.698595,...,20.9945,20.7108,20.659667,65.118955,65.237850,62.581741,55100.0,-33.090909,-22.750000,-20.728929
5,1.047003,0.730313,0.696770,-1.334016,-1.315698,-1.302768,-1.224061,-1.291203,-1.178658,-2.113532,...,28.0620,27.6068,27.264667,52.937189,51.619489,50.330987,23000.0,-30.327869,-14.889336,-14.889336
6,0.635146,0.534904,0.548933,-1.241507,-1.158673,-1.089709,-1.878080,-1.834100,-1.847686,-1.225900,...,29.8835,29.4972,29.245667,53.712769,55.231303,51.984561,29000.0,-35.567010,-18.062827,-16.586538
7,1.343182,1.085069,0.852864,-1.319639,-1.427601,-1.526051,-0.283821,-0.384598,-0.122748,-1.373285,...,60.0945,59.7480,59.097333,54.926018,54.381483,52.929918,173000.0,-52.279635,-52.279635,-52.279635
8,0.977007,0.661013,0.684910,-0.762045,-0.691705,-0.664530,-1.183201,-1.198431,-1.020849,-1.541536,...,61.3000,61.0800,61.000000,70.812028,70.298174,70.252590,50875.0,-37.037037,-29.411765,-27.027027
9,-0.021189,-0.156267,-0.151025,-1.126849,-1.117679,-1.110172,-1.062632,-1.110811,-1.111733,-1.589321,...,22.3375,21.9372,21.755667,48.293919,46.335628,45.786984,22600.0,-47.583643,-29.290618,-26.446281
10,1.188492,1.178079,1.191843,-1.399414,-1.349357,-1.304862,-1.861153,-1.850785,-1.753853,-0.960408,...,28.1415,27.5408,27.146667,63.563370,63.921691,62.681525,13600.0,-20.588235,-10.177706,-9.375000
11,-0.117745,-0.778175,0.016647,-1.034576,-1.028115,-1.004613,-0.791761,-1.045128,-0.598022,-1.332722,...,19.1595,19.3324,19.139667,42.580749,40.769581,41.028622,13900.0,-58.309038,-58.309038,-63.613232
12,0.901328,0.780557,0.818446,-1.271636,-1.226212,-1.192344,-1.648135,-1.651972,-1.625353,-1.330810,...,107.7255,106.2764,105.349333,59.696785,58.136415,55.359218,2279700.0,-34.556213,-17.505995,-16.685714
13,-0.271606,-0.945940,0.036294,1.179703,1.228410,1.254908,0.512283,0.557300,0.245495,0.886326,...,27.5785,27.8104,27.860667,57.651755,58.534731,56.390881,32700.0,-65.538462,-65.538462,-66.863905
14,-0.952306,-1.001237,-0.863672,0.363119,0.505358,0.841580,-0.331937,-0.607492,-0.189212,1.276306,...,13.5255,13.5700,13.531000,54.432049,52.857221,53.695274,65800.0,-53.703704,-53.703704,-53.703704
15,0.042571,-1.236949,-0.039756,0.123948,0.463377,0.774708,-1.264360,-1.326741,-1.284802,-1.373069,...,18.1095,18.0276,17.940333,48.462437,48.803565,47.722315,14000.0,-43.589744,-37.569061,-33.009709
16,0.824741,0.879041,0.766940,-2.700726,-2.585424,-2.466004,-1.396263,-1.729314,-0.885414,1.069017,...,10.3255,10.3532,10.337667,48.675810,51.069007,49.684914,6000.0,-41.891892,-41.891892,-41.891892
17,1.018300,0.655134,0.726070,-1.555864,-1.509030,-1.468692,-1.370758,-1.568731,-1.053269,-1.817911,...,148.0460,146.2148,144.900667,52.120321,52.436622,52.677649,6023600.0,-30.013928,-21.889284,-21.889284
18,1.115898,0.538302,0.479206,-1.262181,-1.223918,-1.188871,-1.406345,-1.487049,-1.230193,-0.819681,...,23.5550,22.8740,22.515333,56.085110,53.851157,56.401189,636400.0,-51.428571,-28.825623,-26.341463
19,1.816283,1.914977,1.987929,-2.228746,-2.087988,-1.975127,-3.634201,-3.407227,-3.597199,-2.691568,...,26.5400,26.3216,26.133333,49.779155,50.324334,50.811558,169700.0,-16.532258,-14.041096,-13.666667
20,1.935366,2.112064,2.163585,-2.500613,-2.359566,-2.245690,-1.192087,-1.861092,-0.854632,0.897446,...,28.4515,28.3308,28.033000,44.674127,50.670110,51.650902,255400.0,-32.227488,-32.227488,-32.227488
21,-0.482646,-0.649214,-0.725058,-0.867968,-0.804801,-0.761650,-1.356808,-1.331525,-1.390412,-0.903630,...,21.1060,20.7724,20.713333,59.250409,59.672220,62.151019,169700.0,-43.272727,-29.974811,-29.750000
22,0.478125,0.135194,0.376839,-1.383806,-1.363919,-1.348919,-1.168813,-1.272769,-1.071469,0.449457,...,28.2520,27.7364,27.406333,53.409795,54.348447,54.866498,136600.0,-12.295082,-6.036217,-6.036217
23,0.581521,0.324280,0.329872,-1.266407,-1.196119,-1.136042,-1.725769,-1.742269,-1.600208,-1.118821,...,30.0305,29.5824,29.360000,55.639923,53.908600,55.028418,6000.0,-31.443299,-15.968586,-14.663462
24,0.838037,0.721484,0.493483,-1.095309,-1.233822,-1.370803,-0.042751,-0.139070,0.101427,-0.018551,...,60.1350,59.8272,59.273333,59.784635,57.943884,56.342900,233000.0,-37.082067,-37.082067,-37.082067
25,1.415232,1.079010,1.119763,-0.490018,-0.451135,-0.446430,-0.658059,-0.740459,-0.409009,-0.970033,...,61.5000,61.1800,61.150000,70.955783,71.174758,71.259563,39350.0,-33.333333,-26.470588,-24.324324
26,-0.265657,-0.281658,-0.336064,-1.220548,-1.202742,-1.188520,-1.228620,-1.266804,-1.258133,-1.800146,...,22.4625,22.0136,21.816333,41.524425,43.109045,43.498643,43700.0,-61.338290,-37.844037,-35.106383
27,0.123665,-0.243648,-0.236587,-1.420448,-1.375771,-1.335206,-1.734555,-1.782959,-1.536478,-1.562535,...,28.3990,27.7124,27.341333,59.243149,60.408995,61.910223,55700.0,-21.000000,-10.177706,-9.662577
28,0.897582,-0.080108,0.701896,-0.903117,-0.910238,-0.899964,-0.563304,-0.810479,-0.368151,-0.876894,...,19.1035,19.2948,19.179333,49.611512,48.308192,46.295087,27700.0,-38.192420,-38.192420,-46.055980
29,0.531926,0.175845,0.183277,-1.305536,-1.265119,-1.233905,-1.536142,-1.589822,-1.436069,-1.184966,...,108.2930,106.5576,105.761000,56.788978,57.274484,57.227332,1027100.0,-40.833333,-20.563549,-19.600000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71139,-0.157736,-0.167056,-0.182091,-0.822505,-0.716211,-0.630552,-1.623080,-1.454243,-1.822148,-1.821959,...,51.5330,51.3840,51.257000,53.065544,53.795353,54.166486,6537203.0,-33.031674,-26.937269,-26.937269
71140,0.055810,-0.014886,-0.087730,-1.686016,-2.343039,-2.624247,1.527943,1.308528,1.771459,1.011719,...,63.0510,62.7820,62.519333,43.291423,44.680036,46.449328,4642675.0,-71.250000,-56.716418,-48.305085
71141,-0.851967,-0.902949,-1.119651,-0.597338,-1.391651,-1.979653,1.886396,1.673000,2.093430,0.685673,...,68.9410,69.0828,69.334333,48.049148,50.675665,51.888366,4458413.0,-37.060703,-37.060703,-37.060703
71142,-1.332140,-1.448402,-1.455892,-1.718986,-1.640087,-1.565770,-2.090010,-2.134882,-1.970063,-2.456412,...,48.2335,48.1224,47.872333,49.636764,51.865373,50.548362,11105195.0,-18.181818,-15.841584,-15.841584
71143,0.268129,0.296580,0.064120,-0.988995,-0.865657,-0.739021,-1.544805,-1.526250,-1.519951,-1.346388,...,50.2240,50.1448,50.038333,41.414050,46.383072,43.469252,4831963.0,-91.489362,-86.432161,-85.148515
71144,-0.431195,-0.744541,-1.213875,-1.850910,-1.919999,-1.927306,0.944181,0.738073,1.131029,-0.068821,...,50.4375,50.1180,49.833667,50.024136,50.465797,48.894520,3315439.0,-91.017964,-56.505576,-54.092527
71145,0.360189,0.471183,0.572128,-2.593701,-2.519948,-2.424883,0.110973,-0.206580,0.408566,-1.767405,...,83.0550,82.8384,82.340000,39.798447,43.346084,41.535890,4461019.0,-63.076923,-61.377246,-61.377246
71146,0.560441,0.587523,0.644262,-0.066658,0.328233,0.743331,-1.604247,-1.418581,-1.812732,-0.447461,...,44.4670,44.2916,44.275000,39.154908,37.748550,39.662067,4933362.0,-84.900990,-84.900990,-84.900990
71147,-0.074492,-0.116069,-0.137389,-2.058062,-2.052927,-2.015965,1.705715,1.429666,1.958100,-2.215440,...,195.5460,194.3452,193.410667,48.704494,52.591051,52.423876,2250872.0,-10.804020,-9.398907,-8.261287
71148,-1.789350,-2.042067,-2.095112,-0.448129,-0.392793,-0.333049,-0.750073,-0.747877,-0.745305,-1.348976,...,25.6730,25.5332,25.501667,46.749660,49.983895,50.445729,1742368.0,-13.533835,-9.424084,-9.424084
71149,-0.232565,-0.301147,-0.402675,-0.373595,-0.061163,0.302718,-1.497864,-1.543590,-1.429314,-1.300950,...,20.4680,20.5464,20.576000,26.283030,32.121548,31.212258,2277948.0,-96.129032,-96.610169,-96.610169
71150,-0.894855,-0.657004,-0.866781,-1.864105,-1.778274,-1.705158,-1.818961,-1.947823,-1.633970,-1.764450,...,26.4255,26.2912,26.100333,41.417228,43.108917,42.749116,1241338.0,-90.598291,-67.948718,-67.948718
71151,0.821950,0.584862,0.203157,-1.013307,-1.032128,-1.024003,-0.288995,-0.550614,0.001101,-1.747149,...,20.7675,20.6724,20.631000,29.538281,33.322259,33.468049,1187089.0,-97.520661,-97.520661,-97.520661
71152,1.781518,2.202856,2.583143,-2.263297,-2.212942,-2.144218,0.984328,0.664012,1.254394,-1.882867,...,224.0255,223.2784,222.337000,50.861887,47.407196,49.244851,36697822.0,-34.244792,-28.618063,-28.618063
71153,-0.097982,-0.207498,-0.249216,-2.500406,-2.653162,-2.544844,1.962825,1.780019,2.174973,0.611225,...,23.2370,23.0472,22.875000,59.095354,56.077625,57.670913,18276667.0,-28.155340,-20.138889,-16.292135
71154,0.852616,0.959469,1.001545,-1.134338,-1.039961,-0.966820,-1.909328,-1.748988,-2.086532,-0.745595,...,47.8845,47.6548,47.433000,64.924501,53.748967,53.740621,7778511.0,-29.856115,-24.411765,-24.411765
71155,2.315503,2.726613,2.827930,-1.869106,-1.829559,-1.783650,-0.318487,-0.752963,0.105333,-1.812517,...,75.5600,74.9492,74.234000,54.414121,47.882768,51.253837,6398132.0,-54.263566,-40.697674,-25.059666
71156,0.420315,0.378234,0.412307,-1.004466,-0.904462,-0.823264,-1.771290,-1.618114,-1.942976,-1.518441,...,51.5750,51.4392,51.306000,61.840112,53.701799,52.704612,6484307.0,-29.857820,-23.247232,-23.247232
71157,0.540805,0.626259,0.654990,-0.827652,-1.617020,-2.172687,1.749486,1.543446,1.985241,0.533762,...,63.0650,62.8488,62.587667,50.000092,45.044618,44.915101,5101030.0,-67.500000,-64.285714,-51.923077
71158,0.098496,0.104136,0.127616,0.136358,-0.581160,-1.214036,2.162698,1.991778,2.323527,0.667153,...,68.9400,69.0432,69.264333,56.305500,52.243299,53.063936,4188703.0,-20.447284,-20.447284,-20.447284
71159,0.719344,0.641616,0.645221,-1.870732,-1.790751,-1.715649,-2.147978,-2.258351,-1.928433,-2.211031,...,48.2820,48.1852,47.951667,54.625101,52.304475,52.422828,6358653.0,-18.376068,-14.191419,-14.191419
71160,0.314826,0.346523,0.243681,-1.057314,-0.957983,-0.850927,-1.383808,-1.433791,-1.275607,-0.834133,...,50.2375,50.1296,50.049333,46.949858,42.556442,46.551742,5535042.0,-87.165775,-81.909548,-80.693069
71161,1.131030,1.268345,1.026108,-1.692608,-1.841823,-1.897613,0.993398,0.829340,1.140825,0.313442,...,50.4730,50.1932,49.882000,57.880133,53.102007,53.415604,2157398.0,-82.558140,-65.137615,-52.014652
71162,0.635740,0.796364,0.953483,-2.667752,-2.652838,-2.573555,0.363470,0.100798,0.609480,-1.542339,...,83.0285,82.8784,82.446000,39.640827,39.030365,41.969221,2836955.0,-88.142292,-66.766467,-66.766467
71163,0.519961,0.548112,0.606830,-0.389004,-0.049126,0.318629,-1.729849,-1.565658,-1.907371,-0.093665,...,44.4480,44.2712,44.258333,47.421951,41.527317,41.720151,1671909.0,-74.009901,-74.009901,-74.009901
71164,0.876924,1.153963,1.176926,-1.796102,-1.867102,-1.875735,2.020381,1.802508,2.226725,-1.292275,...,195.9335,194.7352,193.774667,54.582372,50.961373,53.225812,1374228.0,-9.798995,-9.187279,-7.831325
71165,-0.224234,-0.286502,-0.295423,-0.522506,-0.472341,-0.418674,-0.791020,-0.794297,-0.777113,-1.042113,...,25.7400,25.5820,25.526333,52.656167,48.396588,50.731329,1279977.0,-12.389381,-7.329843,-7.329843
71166,0.597385,0.543350,0.727536,-0.411805,-0.161252,0.132400,-1.364053,-1.458290,-1.240952,-0.915048,...,20.3900,20.4952,20.525000,27.437159,26.141055,32.588222,1100055.0,-98.113208,-98.342541,-98.342541
71167,3.348332,3.240104,2.420948,-1.912248,-1.847180,-1.785149,-1.318741,-1.539205,-1.058511,-1.607249,...,26.4350,26.3172,26.126000,46.237590,39.906499,41.670479,1083528.0,-98.360656,-93.023256,-76.923077
71168,1.103579,0.894302,0.572209,-0.825790,-0.881074,-0.902429,0.000323,-0.226351,0.234583,-1.459575,...,20.7285,20.6664,20.616333,31.454389,30.520911,32.758971,1599371.0,-95.000000,-95.000000,-95.000000

In [37]:
df.to_csv('dataholder.csv',index=False)

In [39]:
df.to_hdf('dataholder.h5py',key='df')

In [42]:
a = pd.read_hdf('dataholder.h5py', key='df')

In [43]:
a

,0,1,10,100,101,102,103,104,105,106,...,sma_20,sma_25,sma_30,ulos_7_14_28,ulos_8_16_32,ulos_9_18_36,volume,wR_14,wR_18,wR_22
0,NaN,1.170187,-1.243305,-0.903178,-0.657303,-0.638543,-0.615087,0.165907,0.106713,-0.022032,...,147.4835,145.8020,144.297000,52.212262,52.341188,50.377367,6378500.0,-36.699164,-26.764855,-25.434363
1,NaN,0.635844,-1.208565,-0.652343,-0.366536,0.058220,0.403852,-0.812737,-1.035622,-0.793344,...,23.3575,22.7516,22.375667,58.605751,59.478761,56.570493,278700.0,-35.555556,-19.928826,-18.211382
2,NaN,0.610523,-2.627184,-0.842300,-0.012545,0.906766,1.551816,-0.447936,-0.681389,-0.695671,...,26.4325,26.2616,25.990333,51.517043,50.994433,52.541772,129200.0,-13.306452,-11.301370,-10.248447
3,NaN,1.992617,-0.474072,-1.272271,-1.251291,-1.055505,-0.810687,0.133028,-0.468656,-0.802408,...,28.3960,28.2516,27.898000,54.418489,54.073401,55.082486,38000.0,-21.563981,-21.563981,-21.563981
4,NaN,0.027102,0.232011,0.993169,1.539801,1.612738,1.485426,-0.940137,-1.401441,-0.981068,...,20.9945,20.7108,20.659667,65.118955,65.237850,62.581741,55100.0,-33.090909,-22.750000,-20.728929
5,NaN,0.730313,-2.433353,-0.730334,-0.571867,-0.336331,0.088864,-0.052030,-0.580973,-0.354262,...,28.0620,27.6068,27.264667,52.937189,51.619489,50.330987,23000.0,-30.327869,-14.889336,-14.889336
6,NaN,0.534904,0.219695,-0.247887,0.679739,1.210816,1.510910,-0.209505,-0.107250,-0.264732,...,29.8835,29.4972,29.245667,53.712769,55.231303,51.984561,29000.0,-35.567010,-18.062827,-16.586538
7,NaN,1.085069,0.335576,-1.321287,-1.177830,-1.294566,-1.291441,1.415635,1.825837,2.013992,...,60.0945,59.7480,59.097333,54.926018,54.381483,52.929918,173000.0,-52.279635,-52.279635,-52.279635
8,NaN,0.661013,-0.908588,-0.182768,0.914164,1.086494,0.985806,-0.109789,-0.460255,-0.483158,...,61.3000,61.0800,61.000000,70.812028,70.298174,70.252590,50875.0,-37.037037,-29.411765,-27.027027
9,NaN,-0.156267,-1.692011,0.218999,0.918534,1.476992,1.523477,-1.180751,-1.243422,-0.838247,...,22.3375,21.9372,21.755667,48.293919,46.335628,45.786984,22600.0,-47.583643,-29.290618,-26.446281
10,NaN,1.178079,-0.280458,-0.607996,-0.138946,0.300935,0.892397,-1.118515,-1.252542,-1.119076,...,28.1415,27.5408,27.146667,63.563370,63.921691,62.681525,13600.0,-20.588235,-10.177706,-9.375000
11,NaN,-0.778175,-0.020655,-1.452069,-1.237708,-1.557056,-1.552927,0.733989,1.105874,0.590047,...,19.1595,19.3324,19.139667,42.580749,40.769581,41.028622,13900.0,-58.309038,-58.309038,-63.613232
12,NaN,0.780557,-1.206337,-0.294787,0.321956,0.969081,1.401556,-0.672646,-0.799826,-0.661758,...,107.7255,106.2764,105.349333,59.696785,58.136415,55.359218,2279700.0,-34.556213,-17.505995,-16.685714
13,NaN,-0.945940,1.779388,0.663429,0.321671,-1.306244,-1.578169,0.355781,0.171090,0.996610,...,27.5785,27.8104,27.860667,57.651755,58.534731,56.390881,32700.0,-65.538462,-65.538462,-66.863905
14,NaN,-1.001237,1.840775,-1.154958,-1.376977,-1.710770,-1.688893,1.564456,2.223361,1.978180,...,13.5255,13.5700,13.531000,54.432049,52.857221,53.695274,65800.0,-53.703704,-53.703704,-53.703704
15,NaN,-1.236949,0.276082,-0.378592,-0.194072,-0.988515,-1.311848,-0.030802,-0.398061,-0.917814,...,18.1095,18.0276,17.940333,48.462437,48.803565,47.722315,14000.0,-43.589744,-37.569061,-33.009709
16,NaN,0.879041,0.911325,-1.224141,0.680204,1.328572,1.382078,0.234769,0.848390,0.652846,...,10.3255,10.3532,10.337667,48.675810,51.069007,49.684914,6000.0,-41.891892,-41.891892,-41.891892
17,NaN,0.655134,-1.377071,-0.942862,-0.742248,-0.624314,-0.726222,-0.141221,-0.266561,-0.238128,...,148.0460,146.2148,144.900667,52.120321,52.436622,52.677649,6023600.0,-30.013928,-21.889284,-21.889284
18,NaN,0.538302,-0.646571,-0.733389,-0.509370,-0.116196,0.180876,-0.981433,-1.125183,-1.231513,...,23.5550,22.8740,22.515333,56.085110,53.851157,56.401189,636400.0,-51.428571,-28.825623,-26.341463
19,NaN,1.914977,-2.267961,-0.958672,-0.268766,0.698134,1.263324,0.079638,-1.297660,-1.519404,...,26.5400,26.3216,26.133333,49.779155,50.324334,50.811558,169700.0,-16.532258,-14.041096,-13.666667
20,NaN,2.112064,0.866919,-1.302494,-1.296364,-1.095092,-1.013427,-0.012569,-0.129963,-0.794015,...,28.4515,28.3308,28.033000,44.674127,50.670110,51.650902,255400.0,-32.227488,-32.227488,-32.227488
21,NaN,-0.649214,-0.053326,0.770943,1.429681,1.620151,1.496003,-1.439103,-1.564478,-1.831466,...,21.1060,20.7724,20.713333,59.250409,59.672220,62.151019,169700.0,-43.272727,-29.974811,-29.750000
22,NaN,0.135194,0.938937,-0.727353,-0.666305,-0.437579,-0.148428,-0.332027,-0.317295,-0.681327,...,28.2520,27.7364,27.406333,53.409795,54.348447,54.866498,136600.0,-12.295082,-6.036217,-6.036217
23,NaN,0.324280,0.116361,-0.485994,0.337941,1.090257,1.433081,-0.806692,-0.809551,-0.614808,...,30.0305,29.5824,29.360000,55.639923,53.908600,55.028418,6000.0,-31.443299,-15.968586,-14.663462
24,NaN,0.721484,0.302706,-1.317334,-1.193271,-1.231491,-1.317527,0.673041,0.978209,1.486139,...,60.1350,59.8272,59.273333,59.784635,57.943884,56.342900,233000.0,-37.082067,-37.082067,-37.082067
25,NaN,1.079010,-1.200465,-0.150983,0.332330,0.940294,0.815957,-1.078257,-1.126374,-1.142363,...,61.5000,61.1800,61.150000,70.955783,71.174758,71.259563,39350.0,-33.333333,-26.470588,-24.324324
26,NaN,-0.281658,-1.833290,0.035925,0.562378,1.372432,1.499359,-1.395218,-1.517348,-1.563026,...,22.4625,22.0136,21.816333,41.524425,43.109045,43.498643,43700.0,-61.338290,-37.844037,-35.106383
27,NaN,-0.243648,-1.379303,-0.731550,-0.350267,0.100891,0.537628,-1.210081,-1.512812,-1.540057,...,28.3990,27.7124,27.341333,59.243149,60.408995,61.910223,55700.0,-21.000000,-10.177706,-9.662577
28,NaN,-0.080108,0.028886,-1.445197,-1.246883,-1.521088,-1.576551,0.994985,0.501349,1.061487,...,19.1035,19.2948,19.179333,49.611512,48.308192,46.295087,27700.0,-38.192420,-38.192420,-46.055980
29,NaN,0.175845,-1.068197,-0.402128,0.049648,0.789368,1.276657,-1.193049,-1.180176,-1.235408,...,108.2930,106.5576,105.761000,56.788978,57.274484,57.227332,1027100.0,-40.833333,-20.563549,-19.600000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142308,-0.157736,-0.167056,-1.385845,1.101554,1.427986,1.388553,1.378259,-1.586142,-1.256776,-0.806581,...,51.5330,51.3840,51.257000,53.065544,53.795353,54.166486,6537203.0,-33.031674,-26.937269,-26.937269
142309,0.055810,-0.014886,0.453951,-1.484034,-1.378058,-1.274158,-1.228844,1.055018,0.984762,1.279849,...,63.0510,62.7820,62.519333,43.291423,44.680036,46.449328,4642675.0,-71.250000,-56.716418,-48.305085
142310,-0.851967,-0.902949,0.811781,-0.785222,-0.808902,0.082097,1.150419,0.208429,0.128088,0.719917,...,68.9410,69.0828,69.334333,48.049148,50.675665,51.888366,4458413.0,-37.060703,-37.060703,-37.060703
142311,-1.332140,-1.448402,-1.891375,-1.247523,-0.867935,-0.755977,-0.725606,0.382393,0.400541,0.863312,...,48.2335,48.1224,47.872333,49.636764,51.865373,50.548362,11105195.0,-18.181818,-15.841584,-15.841584
142312,0.268129,0.296580,-0.792064,-0.334548,0.234868,0.000634,-0.775101,0.827532,1.009255,1.452924,...,50.2240,50.1448,50.038333,41.414050,46.383072,43.469252,4831963.0,-91.489362,-86.432161,-85.148515
142313,-0.431195,-0.744541,-0.219468,-1.346317,-1.258584,-1.193170,-1.187395,0.142731,0.054345,0.231760,...,50.4375,50.1180,49.833667,50.024136,50.465797,48.894520,3315439.0,-91.017964,-56.505576,-54.092527
142314,0.360189,0.471183,-1.715251,-1.480356,-1.258620,-1.189939,-1.154870,0.788280,0.693269,0.993883,...,83.0550,82.8384,82.340000,39.798447,43.346084,41.535890,4461019.0,-63.076923,-61.377246,-61.377246
142315,0.560441,0.587523,-0.717150,1.538221,1.522968,1.428532,1.331317,-1.233610,-1.105245,-0.631149,...,44.4670,44.2916,44.275000,39.154908,37.748550,39.662067,4933362.0,-84.900990,-84.900990,-84.900990
142316,-0.074492,-0.116069,-2.217312,-1.337858,-1.247142,-1.168416,-1.120742,0.985056,0.892964,1.410274,...,195.5460,194.3452,193.410667,48.704494,52.591051,52.423876,2250872.0,-10.804020,-9.398907,-8.261287
142317,-1.789350,-2.042067,-1.092227,0.457872,1.082162,1.403611,1.451889,-0.537295,-0.454970,-0.031370,...,25.6730,25.5332,25.501667,46.749660,49.983895,50.445729,1742368.0,-13.533835,-9.424084,-9.424084
142318,-0.232565,-0.301147,-1.295889,1.055935,1.363265,1.244343,1.155903,-0.181468,-0.091459,-0.179261,...,20.4680,20.5464,20.576000,26.283030,32.121548,31.212258,2277948.0,-96.129032,-96.610169,-96.610169
142319,-0.894855,-0.657004,-1.793135,-1.199998,-1.043522,-0.928330,-1.072108,0.188397,0.304704,0.513667,...,26.4255,26.2912,26.100333,41.417228,43.108917,42.749116,1241338.0,-90.598291,-67.948718,-67.948718
142320,0.821950,0.584862,-1.620705,-1.185519,-0.851558,-0.349344,0.009023,-0.502927,-0.282155,0.220113,...,20.7675,20.6724,20.631000,29.538281,33.322259,33.468049,1187089.0,-97.520661,-97.520661,-97.520661
142321,1.781518,2.202856,-2.156363,-1.427060,-1.268652,-1.164774,-1.125187,0.150307,0.455117,0.456475,...,224.0255,223.2784,222.337000,50.861887,47.407196,49.244851,36697822.0,-34.244792,-28.618063,-28.618063
142322,-0.097982,-0.207498,0.434066,-1.437876,-1.341241,-1.263416,-1.219227,1.066777,1.197582,1.170198,...,23.2370,23.0472,22.875000,59.095354,56.077625,57.670913,18276667.0,-28.155340,-20.138889,-16.292135
142323,0.852616,0.959469,-0.493149,0.302449,0.890342,1.274436,1.275478,-1.224500,-1.911859,-1.818531,...,47.8845,47.6548,47.433000,64.924501,53.748967,53.740621,7778511.0,-29.856115,-24.411765,-24.411765
142324,2.315503,2.726613,-2.226202,-1.320456,-1.204526,-1.103081,-1.039858,-0.470566,-0.177165,-0.253021,...,75.5600,74.9492,74.234000,54.414121,47.882768,51.253837,6398132.0,-54.263566,-40.697674,-25.059666
142325,0.420315,0.378234,-1.031271,0.758643,1.334973,1.338939,1.360290,-2.046172,-1.811542,-1.589892,...,51.5750,51.4392,51.306000,61.840112,53.701799,52.704612,6484307.0,-29.857820,-23.247232,-23.247232
142326,0.540805,0.626259,0.297366,-1.522700,-1.411345,-1.306427,-1.249853,1.061291,1.136228,1.097552,...,63.0650,62.8488,62.587667,50.000092,45.044618,44.915101,5101030.0,-67.500000,-64.285714,-51.923077
142327,0.098496,0.104136,0.586637,-0.518004,-0.819185,0.125432,0.943780,-1.190582,-0.567605,-0.557551,...,68.9400,69.0432,69.264333,56.305500,52.243299,53.063936,4188703.0,-20.447284,-20.447284,-20.447284
142328,0.719344,0.641616,-1.548521,-1.285133,-0.927095,-0.788140,-0.781954,-0.088076,0.235801,0.260931,...,48.2820,48.1852,47.951667,54.625101,52.304475,52.422828,6358653.0,-18.376068,-14.191419,-14.191419
142329,0.314826,0.346523,-0.500231,-0.636929,-0.049423,-0.062279,-1.026479,-0.279736,-0.568808,-0.613986,...,50.2375,50.1296,50.049333,46.949858,42.556442,46.551742,5535042.0,-87.165775,-81.909548,-80.693069
142330,1.131030,1.268345,-0.013059,-1.396822,-1.313896,-1.221561,-1.221338,-0.403352,0.110525,0.085815,...,50.4730,50.1932,49.882000,57.880133,53.102007,53.415604,2157398.0,-82.558140,-65.137615,-52.014652
142331,0.635740,0.796364,-1.419842,-1.510257,-1.319529,-1.215852,-1.183014,0.289720,0.658253,0.570353,...,83.0285,82.8784,82.446000,39.640827,39.030365,41.969221,2836955.0,-88.142292,-66.766467,-66.766467
142332,0.519961,0.548112,-0.142960,1.485475,1.506235,1.448329,1.339888,-1.572997,-1.656872,-1.612689,...,44.4480,44.2712,44.258333,47.421951,41.527317,41.720151,1671909.0,-74.009901,-74.009901,-74.009901
142333,0.876924,1.153963,-2.081434,-1.356976,-1.270325,-1.192293,-1.141779,0.247066,0.628659,0.583519,...,195.9335,194.7352,193.774667,54.582372,50.961373,53.225812,1374228.0,-9.798995,-9.187279,-7.831325
142334,-0.224234,-0.286502,-1.204353,0.134037,0.793164,1.249273,1.369717,-1.287310,-0.967403,-0.872161,...,25.7400,25.5820,25.526333,52.656167,48.396588,50.731329,1279977.0,-12.389381,-7.329843,-7.329843
142335,0.597385,0.543350,-1.302373,0.954788,1.311835,1.241666,1.115881,0.306849,-0.079766,0.000456,...,20.3900,20.4952,20.525000,27.437159,26.141055,32.588222,1100055.0,-98.113208,-98.342541,-98.342541
142336,3.348332,3.240104,-1.722006,-1.277850,-1.127642,-0.979493,-1.087914,-0.012119,0.307773,0.432399,...,26.4350,26.3172,26.126000,46.237590,39.906499,41.670479,1083528.0,-98.360656,-93.023256,-76.923077
142337,1.103579,0.894302,-1.269900,-1.295927,-1.090151,-0.612596,-0.356782,-0.592120,-0.641312,-0.506149,...,20.7285,20.6664,20.616333,31.454389,30.520911,32.758971,1599371.0,-95.000000,-95.000000,-95.000000