In [1]:
import pandas as pd
import pickle

In [2]:
operations = pd.read_pickle("../input/result/buy_sell_model_regr_2017_09_29 22_35_56_516683")

In [3]:
shares = pd.read_pickle("../input/result/buy_sell_model_regr_shares_2017_09_29 22_35_56_516683")

In [4]:
predictions = pd.read_pickle("../input/result/predictions_model_regr_100epoch_qratio_0_2017_09_29 18_15_07_381385")

In [5]:
operations

     Amounts  Capitals       Dates Names Operations  Prices  Transaction Costs
0      205.0     48.40  2015-03-25   xlb        buy   48.52                  5
1        2.0      0.02  2015-03-26   ewh        buy   21.69                  5
2      205.0   9964.17  2015-03-26   xlb       sell   48.63                  5
3      136.0     25.73  2015-03-27   xlv        buy   73.04                  5
4      136.0   9880.73  2015-03-31   xlv       sell   72.50                  5
5      202.0     18.13  2015-04-01   xlp        buy   48.80                  5
6        2.0     57.51  2015-04-02   ewh       sell   22.19                  5
7        2.0      7.81  2015-04-06   ewh        buy   22.35                  5
8      202.0   9959.39  2015-04-07   xlp       sell   49.29                  5
9      178.0      2.41  2015-04-08   xli        buy   55.91                  5
10       2.0     46.13  2015-04-09   ewh       sell   24.36                  5
11       1.0     16.89  2015-04-10   xlf        buy   24.24                  5
12     178.0  10152.55  2015-04-10   xli       sell   56.97                  5
13     417.0      1.94  2015-04-13   xlf        buy   24.33                  5
14     418.0  10221.22  2015-04-16   xlf       sell   24.46                  5
15     246.0     14.60  2015-04-17   xlk        buy   41.47                  5
16     246.0  10649.10  2015-04-27   xlk       sell   43.25                  5
17     129.0     27.40  2015-04-28   xle        buy   82.30                  5
18     129.0  10721.66  2015-04-29   xle       sell   82.94                  5
19     149.0     31.87  2015-04-30   xlv        buy   71.71                  5
20       1.0      2.85  2015-05-01   ewh        buy   24.02                  5
21     149.0  10895.71  2015-05-04   xlv       sell   73.14                  5
22       1.0  10915.02  2015-05-04   ewh       sell   24.31                  5
23     370.0     28.32  2015-05-05   ewg        buy   29.41                  5
24     370.0  11263.92  2015-05-08   ewg       sell   30.38                  5
25     257.0     20.31  2015-05-11   xlu        buy   43.73                  5
26     257.0  11241.07  2015-05-12   xlu       sell   43.68                  5
27     221.0     24.74  2015-05-13   xlb        buy   50.73                  5
28     221.0  11403.45  2015-05-15   xlb       sell   51.51                  5
29     215.0      3.45  2015-05-18   ewj        buy   53.00                  5
..       ...       ...         ...   ...        ...     ...                ...
289   1083.0      9.78  2016-10-14   ewj        buy   49.36                  5
290   1083.0  53808.22  2016-10-18   ewj       sell   49.68                  5
291    769.0      3.98  2016-10-19   xlv        buy   69.96                  5
292    769.0  54051.99  2016-10-20   xlv       sell   70.29                  5
293   1137.0      5.38  2016-10-21   xlk        buy   47.53                  5
294   1137.0  54565.01  2016-10-24   xlk       sell   47.99                  5
295    300.0    116.01  2016-10-25   dia        buy  181.48                  5
296      1.0     42.05  2016-10-26   xlv        buy   68.96                  5
297    300.0  54568.05  2016-10-26   dia       sell  181.77                  5
298   1040.0     15.05  2016-10-27   xlp        buy   52.45                  5
299      1.0     79.33  2016-10-27   xlv       sell   69.28                  5
300      2.0     22.61  2016-10-28   ewg        buy   25.86                  5
301   1040.0  54794.41  2016-10-28   xlp       sell   52.67                  5
302    813.0     25.73  2016-10-31   xlv        buy   67.36                  5
303      2.0     72.55  2016-10-31   ewg       sell   25.91                  5
304    813.0  54538.55  2016-11-01   xlv       sell   67.00                  5
305   1138.0      0.59  2016-11-02   xlu        buy   47.92                  5
306   1138.0  54733.39  2016-11-03   xlu       sell   48.10                  5
307    306.0     43.13  2016-11-04   dia        buy  178.71                  5
308      1.0     17.65  2016-11-07   ewa        buy   20.48                  5
309      1.0     33.18  2016-11-09   ewa       sell   20.53                  5
310      1.0      7.22  2016-11-10   ewh        buy   20.96                  5
311    306.0  57570.00  2016-11-10   dia       sell  188.13                  5
312    828.0     52.12  2016-11-11   xle        buy   69.46                  5
313      1.0     21.88  2016-11-14   ewg        buy   25.24                  5
314    828.0  59483.84  2016-11-15   xle       sell   71.82                  5
315      1.0  59504.20  2016-11-15   ewg       sell   25.36                  5
316   1204.0     21.60  2016-11-16   ewj        buy   49.40                  5
317   1204.0  60385.16  2016-11-17   ewj       sell   50.14                  5
318      1.0  60400.87  2016-11-17   ewh       sell   20.71                  5

[319 rows x 7 columns]

In [9]:
shares

,dia,ewa,ewc,ewg,ewh,ewj,eww,spy,xlb,xle,xlf,xli,xlk,xlp,xlu,xlv,xly
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,205.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,205.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,136.0,0.0
4,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,202.0,0.0,0.0,0.0
6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,202.0,0.0,0.0,0.0
7,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,202.0,0.0,0.0,0.0
8,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,178.0,0.0,0.0,0.0,0.0,0.0
10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,178.0,0.0,0.0,0.0,0.0,0.0
11,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,178.0,0.0,0.0,0.0,0.0,0.0
12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
13,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,418.0,0.0,0.0,0.0,0.0,0.0,0.0
14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,246.0,0.0,0.0,0.0,0.0
16,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,129.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,149.0,0.0
20,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,149.0,0.0
21,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23,0.0,0.0,0.0,370.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,257.0,0.0,0.0
26,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,221.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29,0.0,0.0,0.0,0.0,0.0,215.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
289,0.0,0.0,0.0,0.0,0.0,1083.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
290,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
291,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,769.0,0.0
292,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
293,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1137.0,0.0,0.0,0.0,0.0
294,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
295,300.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
296,300.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
297,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
298,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1040.0,0.0,1.0,0.0
299,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1040.0,0.0,0.0,0.0
300,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1040.0,0.0,0.0,0.0
301,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
302,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,813.0,0.0
303,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,813.0,0.0
304,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
305,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1138.0,0.0,0.0
306,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
307,306.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
308,306.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
309,306.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
310,306.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
311,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
312,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,828.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
313,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,828.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
314,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
315,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
316,0.0,0.0,0.0,0.0,1.0,1204.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
317,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
318,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [16]:
predictions

        Actual        Date Name  Prediction
0    -0.807523  2015-03-24  ewa   -0.490002
1    -0.764449  2015-03-24  ewc   -0.528527
2    -0.507665  2015-03-24  ewg   -0.454919
3     0.433544  2015-03-24  ewh   -0.313029
4    -0.229484  2015-03-24  ewj   -0.567168
5    -0.896743  2015-03-24  eww   -0.556362
6    -0.898692  2015-03-24  spy   -0.644224
7    -0.807864  2015-03-24  xlb   -1.047506
8     0.861828  2015-03-24  xle   -0.126553
9    -0.921718  2015-03-24  xlf   -0.585888
10   -0.935487  2015-03-24  xli   -0.696335
11   -0.988370  2015-03-24  xlk   -0.669667
12   -0.241347  2015-03-24  xlp   -0.732554
13   -0.823719  2015-03-24  xlu   -0.654782
14   -0.949170  2015-03-24  xlv   -0.534735
15   -0.925553  2015-03-24  xly   -0.463583
16   -0.243696  2015-03-25  dia   -0.107562
17   -0.746395  2015-03-25  ewa   -0.101283
18   -0.214558  2015-03-25  ewc   -0.370069
19   -0.579714  2015-03-25  ewg    0.117312
20    0.227028  2015-03-25  ewh    0.053281
21   -0.767753  2015-03-25  ewj   -0.369739
22   -0.926005  2015-03-25  eww   -0.147243
23   -0.233740  2015-03-25  spy   -0.147822
24    0.222905  2015-03-25  xlb    0.303703
25   -0.116174  2015-03-25  xle   -0.376818
26   -0.083210  2015-03-25  xlf    0.045038
27   -0.263922  2015-03-25  xli   -0.077655
28    0.072494  2015-03-25  xlk    0.156862
29   -0.406925  2015-03-25  xlp    0.023027
...        ...         ...  ...         ...
7109  0.808626  2016-11-16  ewh    0.417282
7110  0.904782  2016-11-16  ewj    0.711291
7111 -0.655828  2016-11-16  eww   -0.260234
7112  0.473109  2016-11-16  spy    0.206968
7113  0.041324  2016-11-16  xlb    0.095041
7114 -0.586965  2016-11-16  xle   -0.842631
7115  0.879231  2016-11-16  xlf    0.245441
7116  0.209313  2016-11-16  xli    0.218609
7117  0.562814  2016-11-16  xlk    0.050734
7118 -0.175436  2016-11-16  xlp   -0.080826
7119  0.021539  2016-11-16  xlu   -0.235281
7120  0.379119  2016-11-16  xlv    0.143460
7121  0.835255  2016-11-16  xly    0.209906
7122 -0.416740  2016-11-17  dia    0.086344
7123 -0.686647  2016-11-17  ewa   -0.089742
7124  0.156070  2016-11-17  ewc    0.269079
7125 -0.724332  2016-11-17  ewg   -0.006100
7126  0.281873  2016-11-17  ewh    0.224224
7127 -0.904389  2016-11-17  ewj   -0.783425
7128 -0.992702  2016-11-17  eww   -0.303804
7129 -0.220094  2016-11-17  spy    0.034341
7130 -0.143657  2016-11-17  xlb    0.250108
7131  0.387940  2016-11-17  xle   -0.266853
7132  0.000000  2016-11-17  xlf    0.300010
7133 -0.032604  2016-11-17  xli    0.177977
7134 -0.084188  2016-11-17  xlk    0.235585
7135 -0.340952  2016-11-17  xlp   -0.010903
7136 -0.292711  2016-11-17  xlu    0.042549
7137 -0.787412  2016-11-17  xlv   -0.290974
7138 -0.297648  2016-11-17  xly    0.031010

[7139 rows x 4 columns]

In [18]:
sum((predictions.Actual / predictions.Prediction) > 0) / predictions.shape[0]

0.74029976187141056

In [21]:
from sklearn.metrics import confusion_matrix

In [34]:
y_true = predictions.Actual > 0
y_pred = predictions.Prediction > 0
tn, fp, fn, tp = confusion_matrix(y_true, y_pred).ravel()
(tn, fp, fn, tp)

(2539, 985, 839, 2776)

In [25]:
unique_dates = predictions.Date.unique()

In [73]:
max_df = pd.DataFrame(columns=predictions.columns)
# append only positive max samples for any given dates
for date in unique_dates:
    try:
        max_pos_idx = predictions.loc[(predictions.Date == date) & (predictions.Prediction > 0)].Prediction.idxmax()
        max_df = max_df.append(predictions.iloc[max_pos_idx])
    except:
        continue
# append all negative samples
max_df = max_df.append(predictions.loc[predictions.Prediction < 0])

In [75]:
y_true = max_df.Actual > 0
y_pred = max_df.Prediction > 0
tn, fp, fn, tp = confusion_matrix(y_true, y_pred).ravel()
(tn, fp, fn, tp)

(2539, 80, 839, 311)

In [78]:
(311)/(311+80) # max

0.7953964194373402

In [79]:
(2776)/(2776+985) # all

0.7381015687317203

In [80]:
(tn/(tn+fn))

0.75162818235642392