In [1]:
import pandas as pd
import numpy as np
pd.options.display.max_rows = 999

In [2]:
class BuySell:

    def __init__(self, capital):
        self.initial_capital = capital
        self.current_capital = capital
        self.share_amount = 0


    def buyandhold(self, dataframe):
        """

        Args:
            dataframe: (pd.DataFrame) should contains price and directive, date columns

        Returns: (float) profit

        """
        first_price = dataframe.iloc[0].loc['price']
        last_price  = dataframe.iloc[-1].loc['price']

        self.current_capital, self.share_amount = BuySell._buy(self.initial_capital, first_price)
        money, self.share_amount = BuySell._sell(self.share_amount, last_price)
        self.current_capital += money

        profit = self.current_capital - self.initial_capital

        return profit

    @staticmethod
    def _buy(money, price):
        """buys if appliable
        Returns: (float, int) current_money, share_amount"""

        remaining_money = money
        share_amount = 0

        if money > price:
            share_amount = int(money / price)
            remaining_money = money - share_amount * price

        return remaining_money, share_amount

    @staticmethod
    def _sell(share_amount, price):
        """sells all shares :)
        Returns: (float, int) current_money, share_amount"""
        money = share_amount * price
        return money, 0



    def process(self, dataframe):
        """

        Args:
            dataframe: (pd.DataFrame) should contains price and directive, date columns

        Returns: (float) profit

        """
        capital_list = list()
        share_amount_list = list()

        for idx,row in dataframe.iterrows():
            if row['directive'] == 'buy':
                remaining_money, share_amount = BuySell._buy(self.current_capital, row['price'])
                self.current_capital = remaining_money
                self.share_amount += share_amount

            if row['directive'] == 'sell':
                money, share_amount = BuySell._sell(self.share_amount, row['price'])
                self.current_capital += money
                self.share_amount = share_amount
            capital_list.append(self.current_capital)
            share_amount_list.append(self.share_amount)

        dataframe.loc[:,'current_capital'] = capital_list
        dataframe.loc[:,'share_amount'] = share_amount_list
        dataframe.loc[:,'total_capital'] = dataframe['current_capital'] + dataframe['share_amount']*dataframe['price']

        dataframe.loc[:,'profit'] = dataframe['total_capital'] - self.initial_capital


        return dataframe

In [3]:
def label_to_directives(row):
    row = row[['pbuy','psell','phold']]
    argmax_idx = np.argmax(row.values)

    if argmax_idx == 0:
        return 'buy'
    if argmax_idx == 1:
        return 'sell'
    return 'hold'

In [9]:
np.random.seed(42)
initial_capital = 100000
# size = 100
# fake_dataframe = pd.DataFrame({'price':np.random.randint(100,150, size=size),
#                                'directive':np.random.choice(['buy','hold','sell'], size=size, replace=True),
#      'name':np.random.choice(['xlp','xlu','xlv','xly','dia','ewa','ewc','ewg','ewh','ewj','eww','spy','xlb','xle','xlf','xli','xlk'], size=size, replace=True)})

In [18]:
dataframe = pd.read_csv('../experiment/finance_cnn_exp1_xlk_only/prediction_results.csv')
dataframe['directive'] = dataframe.apply(label_to_directives, axis=1)
dataframe['price'] = dataframe['raw_adjusted_close'].values
buysell = BuySell(capital=initial_capital)
result_df = buysell.process(dataframe)
subset = ['date','price','directive','current_capital','share_amount','total_capital', 'profit']
result_df[subset]

,date,price,directive,current_capital,share_amount,total_capital,profit
0,2015-03-05,42.92,sell,100000.00,0,100000.00,0.00
1,2015-03-06,42.39,buy,1.99,2359,100000.00,0.00
2,2015-03-09,42.59,hold,1.99,2359,100471.80,471.80
3,2015-03-10,41.72,hold,1.99,2359,98419.47,-1580.53
4,2015-03-11,41.45,hold,1.99,2359,97782.54,-2217.46
5,2015-03-12,41.72,hold,1.99,2359,98419.47,-1580.53
6,2015-03-13,41.49,hold,1.99,2359,97876.90,-2123.10
7,2015-03-16,41.98,hold,1.99,2359,99032.81,-967.19
8,2015-03-17,41.99,hold,1.99,2359,99056.40,-943.60
9,2015-03-18,42.56,hold,1.99,2359,100401.03,401.03
10,2015-03-19,42.44,hold,1.99,2359,100117.95,117.95
11,2015-03-20,42.54,hold,1.99,2359,100353.85,353.85
12,2015-03-23,42.54,hold,1.99,2359,100353.85,353.85
13,2015-03-24,42.40,hold,1.99,2359,100023.59,23.59
14,2015-03-25,41.31,hold,1.99,2359,97452.28,-2547.72
15,2015-03-26,41.34,buy,1.99,2359,97523.05,-2476.95
16,2015-03-27,41.37,buy,1.99,2359,97593.82,-2406.18
17,2015-03-30,41.87,hold,1.99,2359,98773.32,-1226.68
18,2015-03-31,41.44,hold,1.99,2359,97758.95,-2241.05
19,2015-04-01,41.38,hold,1.99,2359,97617.41,-2382.59
20,2015-04-02,41.37,hold,1.99,2359,97593.82,-2406.18
21,2015-04-06,41.77,buy,1.99,2359,98537.42,-1462.58
22,2015-04-07,41.68,hold,1.99,2359,98325.11,-1674.89
23,2015-04-08,41.81,hold,1.99,2359,98631.78,-1368.22
24,2015-04-09,41.92,hold,1.99,2359,98891.27,-1108.73
25,2015-04-10,42.08,hold,1.99,2359,99268.71,-731.29
26,2015-04-13,41.96,hold,1.99,2359,98985.63,-1014.37
27,2015-04-14,41.83,hold,1.99,2359,98678.96,-1321.04
28,2015-04-15,42.20,hold,1.99,2359,99551.79,-448.21
29,2015-04-16,42.05,hold,1.99,2359,99197.94,-802.06
30,2015-04-17,41.47,hold,1.99,2359,97829.72,-2170.28
31,2015-04-20,42.18,hold,1.99,2359,99504.61,-495.39
32,2015-04-21,42.16,hold,1.99,2359,99457.43,-542.57
33,2015-04-22,42.59,buy,1.99,2359,100471.80,471.80
34,2015-04-23,42.76,hold,1.99,2359,100872.83,872.83
35,2015-04-24,43.13,hold,1.99,2359,101745.66,1745.66
36,2015-04-27,43.25,hold,1.99,2359,102028.74,2028.74
37,2015-04-28,43.39,hold,1.99,2359,102359.00,2359.00
38,2015-04-29,43.18,hold,1.99,2359,101863.61,1863.61
39,2015-04-30,42.58,hold,1.99,2359,100448.21,448.21
40,2015-05-01,43.10,hold,1.99,2359,101674.89,1674.89
41,2015-05-04,43.14,hold,1.99,2359,101769.25,1769.25
42,2015-05-05,42.47,hold,1.99,2359,100188.72,188.72
43,2015-05-06,42.11,hold,1.99,2359,99339.48,-660.52
44,2015-05-07,42.42,hold,1.99,2359,100070.77,70.77
45,2015-05-08,43.03,hold,1.99,2359,101509.76,1509.76
46,2015-05-11,42.81,hold,1.99,2359,100990.78,990.78
47,2015-05-12,42.58,hold,1.99,2359,100448.21,448.21
48,2015-05-13,42.76,hold,1.99,2359,100872.83,872.83
49,2015-05-14,43.45,hold,1.99,2359,102500.54,2500.54
50,2015-05-15,43.31,hold,1.99,2359,102170.28,2170.28
51,2015-05-18,43.52,hold,1.99,2359,102665.67,2665.67
52,2015-05-19,43.41,hold,1.99,2359,102406.18,2406.18
53,2015-05-20,43.44,hold,1.99,2359,102476.95,2476.95
54,2015-05-21,43.63,hold,1.99,2359,102925.16,2925.16
55,2015-05-22,43.60,hold,1.99,2359,102854.39,2854.39
56,2015-05-26,42.97,hold,1.99,2359,101368.22,1368.22
57,2015-05-27,43.78,hold,1.99,2359,103279.01,3279.01
58,2015-05-28,43.69,hold,1.99,2359,103066.70,3066.70
59,2015-05-29,43.37,buy,1.99,2359,102311.82,2311.82
60,2015-06-01,43.49,hold,1.99,2359,102594.90,2594.90
61,2015-06-02,43.40,hold,1.99,2359,102382.59,2382.59
62,2015-06-03,43.49,hold,1.99,2359,102594.90,2594.90
63,2015-06-04,43.09,sell,101651.30,0,101651.30,1651.30
64,2015-06-05,42.95,sell,101651.30,0,101651.30,1651.30
65,2015-06-08,42.47,hold,101651.30,0,101651.30,1651.30
66,2015-06-09,42.37,hold,101651.30,0,101651.30,1651.30
67,2015-06-10,43.03,hold,101651.30,0,101651.30,1651.30
68,2015-06-11,43.05,hold,101651.30,0,101651.30,1651.30
69,2015-06-12,42.67,hold,101651.30,0,101651.30,1651.30
70,2015-06-15,42.41,hold,101651.30,0,101651.30,1651.30
71,2015-06-16,42.69,hold,101651.30,0,101651.30,1651.30
72,2015-06-17,42.71,hold,101651.30,0,101651.30,1651.30
73,2015-06-18,43.09,hold,101651.30,0,101651.30,1651.30
74,2015-06-19,42.54,hold,101651.30,0,101651.30,1651.30
75,2015-06-22,42.89,hold,101651.30,0,101651.30,1651.30
76,2015-06-23,42.92,hold,101651.30,0,101651.30,1651.30
77,2015-06-24,42.72,hold,101651.30,0,101651.30,1651.30
78,2015-06-25,42.62,hold,101651.30,0,101651.30,1651.30
79,2015-06-26,42.26,hold,101651.30,0,101651.30,1651.30
80,2015-06-29,41.36,hold,101651.30,0,101651.30,1651.30
81,2015-06-30,41.40,hold,101651.30,0,101651.30,1651.30
82,2015-07-01,41.68,hold,101651.30,0,101651.30,1651.30
83,2015-07-02,41.74,hold,101651.30,0,101651.30,1651.30
84,2015-07-06,41.57,buy,12.65,2445,101651.30,1651.30
85,2015-07-07,41.63,hold,12.65,2445,101798.00,1798.00
86,2015-07-08,40.95,hold,12.65,2445,100135.40,135.40
87,2015-07-09,40.79,hold,12.65,2445,99744.20,-255.80
88,2015-07-10,41.44,buy,12.65,2445,101333.45,1333.45
89,2015-07-13,42.07,buy,12.65,2445,102873.80,2873.80
90,2015-07-14,42.23,buy,12.65,2445,103265.00,3265.00
91,2015-07-15,42.24,hold,12.65,2445,103289.45,3289.45
92,2015-07-16,42.78,hold,12.65,2445,104609.75,4609.75
93,2015-07-17,43.44,hold,12.65,2445,106223.45,6223.45
94,2015-07-20,43.67,hold,12.65,2445,106785.80,6785.80
95,2015-07-21,43.38,hold,12.65,2445,106076.75,6076.75
96,2015-07-22,42.68,hold,12.65,2445,104365.25,4365.25
97,2015-07-23,42.59,buy,12.65,2445,104145.20,4145.20
98,2015-07-24,42.36,buy,12.65,2445,103582.85,3582.85
99,2015-07-27,41.98,hold,12.65,2445,102653.75,2653.75
100,2015-07-28,42.36,hold,12.65,2445,103582.85,3582.85
101,2015-07-29,42.64,hold,12.65,2445,104267.45,4267.45
102,2015-07-30,42.72,hold,12.65,2445,104463.05,4463.05
103,2015-07-31,42.58,hold,12.65,2445,104120.75,4120.75
104,2015-08-03,42.35,hold,12.65,2445,103558.40,3558.40
105,2015-08-04,42.10,hold,12.65,2445,102947.15,2947.15
106,2015-08-05,42.51,hold,12.65,2445,103949.60,3949.60
107,2015-08-06,42.09,hold,12.65,2445,102922.70,2922.70
108,2015-08-07,42.12,hold,12.65,2445,102996.05,2996.05
109,2015-08-10,42.78,hold,12.65,2445,104609.75,4609.75
110,2015-08-11,42.14,hold,12.65,2445,103044.95,3044.95
111,2015-08-12,42.33,hold,12.65,2445,103509.50,3509.50
112,2015-08-13,42.21,hold,12.65,2445,103216.10,3216.10
113,2015-08-14,42.42,hold,12.65,2445,103729.55,3729.55
114,2015-08-17,42.66,hold,12.65,2445,104316.35,4316.35
115,2015-08-18,42.44,hold,12.65,2445,103778.45,3778.45
116,2015-08-19,42.16,buy,12.65,2445,103093.85,3093.85
117,2015-08-20,41.13,buy,12.65,2445,100575.50,575.50
118,2015-08-21,39.56,hold,12.65,2445,96736.85,-3263.15
119,2015-08-24,38.14,hold,12.65,2445,93264.95,-6735.05
120,2015-08-25,37.70,hold,12.65,2445,92189.15,-7810.85
121,2015-08-26,39.60,hold,12.65,2445,96834.65,-3165.35
122,2015-08-27,40.52,hold,12.65,2445,99084.05,-915.95
123,2015-08-28,40.60,hold,12.65,2445,99279.65,-720.35
124,2015-08-31,40.26,hold,12.65,2445,98448.35,-1551.65
125,2015-09-01,39.00,hold,12.65,2445,95367.65,-4632.35
126,2015-09-02,39.88,hold,12.65,2445,97519.25,-2480.75
127,2015-09-03,39.91,hold,12.65,2445,97592.60,-2407.40
128,2015-09-04,39.30,hold,12.65,2445,96101.15,-3898.85
129,2015-09-08,40.40,hold,12.65,2445,98790.65,-1209.35
130,2015-09-09,39.87,hold,12.65,2445,97494.80,-2505.20
131,2015-09-10,40.27,hold,12.65,2445,98472.80,-1527.20
132,2015-09-11,40.46,hold,12.65,2445,98937.35,-1062.65
133,2015-09-14,40.36,hold,12.65,2445,98692.85,-1307.15
134,2015-09-15,40.88,hold,12.65,2445,99964.25,-35.75
135,2015-09-16,41.05,hold,12.65,2445,100379.90,379.90
136,2015-09-17,40.77,buy,12.65,2445,99695.30,-304.70
137,2015-09-18,40.06,hold,12.65,2445,97959.35,-2040.65
138,2015-09-21,40.46,hold,12.65,2445,98937.35,-1062.65
139,2015-09-22,39.78,hold,12.65,2445,97274.75,-2725.25
140,2015-09-23,39.88,hold,12.65,2445,97519.25,-2480.75
141,2015-09-24,39.88,hold,12.65,2445,97519.25,-2480.75
142,2015-09-25,39.81,hold,12.65,2445,97348.10,-2651.90
143,2015-09-28,38.90,hold,12.65,2445,95123.15,-4876.85
144,2015-09-29,38.73,hold,12.65,2445,94707.50,-5292.50
145,2015-09-30,39.50,buy,12.65,2445,96590.15,-3409.85
146,2015-10-01,39.52,hold,12.65,2445,96639.05,-3360.95
147,2015-10-02,40.08,buy,12.65,2445,98008.25,-1991.75
148,2015-10-05,40.85,buy,12.65,2445,99890.90,-109.10
149,2015-10-06,40.92,buy,12.65,2445,100062.05,62.05
150,2015-10-07,41.11,buy,12.65,2445,100526.60,526.60
151,2015-10-08,41.30,hold,12.65,2445,100991.15,991.15
152,2015-10-09,41.48,buy,12.65,2445,101431.25,1431.25
153,2015-10-12,41.53,buy,12.65,2445,101553.50,1553.50
154,2015-10-13,41.44,hold,12.65,2445,101333.45,1333.45
155,2015-10-14,41.36,hold,12.65,2445,101137.85,1137.85
156,2015-10-15,41.88,hold,12.65,2445,102409.25,2409.25
157,2015-10-16,41.99,hold,12.65,2445,102678.20,2678.20
158,2015-10-19,42.13,hold,12.65,2445,103020.50,3020.50
159,2015-10-20,42.02,hold,12.65,2445,102751.55,2751.55
160,2015-10-21,41.70,hold,12.65,2445,101969.15,1969.15
161,2015-10-22,42.64,hold,12.65,2445,104267.45,4267.45
162,2015-10-23,43.83,hold,12.65,2445,107177.00,7177.00
163,2015-10-26,43.66,hold,12.65,2445,106761.35,6761.35
164,2015-10-27,43.41,hold,12.65,2445,106150.10,6150.10
165,2015-10-28,44.06,hold,12.65,2445,107739.35,7739.35
166,2015-10-29,43.94,hold,12.65,2445,107445.95,7445.95
167,2015-10-30,43.65,hold,12.65,2445,106736.90,6736.90
168,2015-11-02,44.04,hold,12.65,2445,107690.45,7690.45
169,2015-11-03,44.27,hold,12.65,2445,108252.80,8252.80
170,2015-11-04,44.32,hold,12.65,2445,108375.05,8375.05
171,2015-11-05,44.19,hold,12.65,2445,108057.20,8057.20
172,2015-11-06,44.34,hold,12.65,2445,108423.95,8423.95
173,2015-11-09,43.91,hold,12.65,2445,107372.60,7372.60
174,2015-11-10,43.62,hold,12.65,2445,106663.55,6663.55
175,2015-11-11,43.60,hold,12.65,2445,106614.65,6614.65
176,2015-11-12,43.22,hold,12.65,2445,105685.55,5685.55
177,2015-11-13,42.37,hold,12.65,2445,103607.30,3607.30
178,2015-11-16,43.02,hold,12.65,2445,105196.55,5196.55
179,2015-11-17,43.03,hold,12.65,2445,105221.00,5221.00
180,2015-11-18,43.68,hold,12.65,2445,106810.25,6810.25
181,2015-11-19,43.88,hold,12.65,2445,107299.25,7299.25
182,2015-11-20,44.20,hold,12.65,2445,108081.65,8081.65
183,2015-11-23,43.94,hold,12.65,2445,107445.95,7445.95
184,2015-11-24,43.95,hold,12.65,2445,107470.40,7470.40
185,2015-11-25,43.81,hold,12.65,2445,107128.10,7128.10
186,2015-11-27,43.91,hold,12.65,2445,107372.60,7372.60
187,2015-11-30,43.96,hold,12.65,2445,107494.85,7494.85
188,2015-12-01,44.35,hold,12.65,2445,108448.40,8448.40
189,2015-12-02,44.07,hold,12.65,2445,107763.80,7763.80
190,2015-12-03,43.50,hold,12.65,2445,106370.15,6370.15
191,2015-12-04,44.57,hold,12.65,2445,108986.30,8986.30
192,2015-12-07,44.35,sell,108448.40,0,108448.40,8448.40
193,2015-12-08,44.24,hold,108448.40,0,108448.40,8448.40
194,2015-12-09,43.59,hold,108448.40,0,108448.40,8448.40
195,2015-12-10,43.71,hold,108448.40,0,108448.40,8448.40
196,2015-12-11,42.80,hold,108448.40,0,108448.40,8448.40
197,2015-12-14,43.13,hold,108448.40,0,108448.40,8448.40
198,2015-12-15,43.32,hold,108448.40,0,108448.40,8448.40
199,2015-12-16,43.91,hold,108448.40,0,108448.40,8448.40
200,2015-12-17,43.22,hold,108448.40,0,108448.40,8448.40
201,2015-12-18,42.17,hold,108448.40,0,108448.40,8448.40
202,2015-12-21,42.60,hold,108448.40,0,108448.40,8448.40
203,2015-12-22,42.91,hold,108448.40,0,108448.40,8448.40
204,2015-12-23,43.27,hold,108448.40,0,108448.40,8448.40
205,2015-12-24,43.25,hold,108448.40,0,108448.40,8448.40
206,2015-12-28,43.22,hold,108448.40,0,108448.40,8448.40
207,2015-12-29,43.81,hold,108448.40,0,108448.40,8448.40
208,2015-12-30,43.44,hold,108448.40,0,108448.40,8448.40
209,2015-12-31,42.83,buy,2.84,2532,108448.40,8448.40
210,2016-01-04,42.27,buy,2.84,2532,107030.48,7030.48
211,2016-01-05,42.16,hold,2.84,2532,106751.96,6751.96
212,2016-01-06,41.64,buy,2.84,2532,105435.32,5435.32
213,2016-01-07,40.41,buy,2.84,2532,102320.96,2320.96
214,2016-01-08,40.09,hold,2.84,2532,101510.72,1510.72
215,2016-01-11,40.35,hold,2.84,2532,102169.04,2169.04
216,2016-01-12,40.83,hold,2.84,2532,103384.40,3384.40
217,2016-01-13,39.73,hold,2.84,2532,100599.20,599.20
218,2016-01-14,40.48,hold,2.84,2532,102498.20,2498.20
219,2016-01-15,39.34,hold,2.84,2532,99611.72,-388.28
220,2016-01-19,39.38,hold,2.84,2532,99713.00,-287.00
221,2016-01-20,39.07,hold,2.84,2532,98928.08,-1071.92
222,2016-01-21,39.29,hold,2.84,2532,99485.12,-514.88
223,2016-01-22,40.38,hold,2.84,2532,102245.00,2245.00
224,2016-01-25,39.91,hold,2.84,2532,101054.96,1054.96
225,2016-01-26,40.30,hold,2.84,2532,102042.44,2042.44
226,2016-01-27,39.47,hold,2.84,2532,99940.88,-59.12
227,2016-01-28,39.98,hold,2.84,2532,101232.20,1232.20
228,2016-01-29,41.24,hold,2.84,2532,104422.52,4422.52
229,2016-02-01,41.39,hold,2.84,2532,104802.32,4802.32
230,2016-02-02,40.65,hold,2.84,2532,102928.64,2928.64
231,2016-02-03,40.60,hold,2.84,2532,102802.04,2802.04
232,2016-02-04,40.64,hold,2.84,2532,102903.32,2903.32
233,2016-02-05,39.50,hold,2.84,2532,100016.84,16.84
234,2016-02-08,38.93,hold,2.84,2532,98573.60,-1426.40
235,2016-02-09,38.75,hold,2.84,2532,98117.84,-1882.16
236,2016-02-10,38.83,buy,2.84,2532,98320.40,-1679.60
237,2016-02-11,38.73,hold,2.84,2532,98067.20,-1932.80
238,2016-02-12,39.27,buy,2.84,2532,99434.48,-565.52
239,2016-02-16,39.97,buy,2.84,2532,101206.88,1206.88
240,2016-02-17,40.79,buy,2.84,2532,103283.12,3283.12
241,2016-02-18,40.63,buy,2.84,2532,102878.00,2878.00
242,2016-02-19,40.66,buy,2.84,2532,102953.96,2953.96
243,2016-02-22,41.20,buy,2.84,2532,104321.24,4321.24
244,2016-02-23,40.55,hold,2.84,2532,102675.44,2675.44
245,2016-02-24,40.86,buy,2.84,2532,103460.36,3460.36
246,2016-02-25,41.37,buy,2.84,2532,104751.68,4751.68
247,2016-02-26,41.26,buy,2.84,2532,104473.16,4473.16
248,2016-02-29,40.97,buy,2.84,2532,103738.88,3738.88
249,2016-03-01,42.19,buy,2.84,2532,106827.92,6827.92
250,2016-03-02,42.31,buy,2.84,2532,107131.76,7131.76
251,2016-03-03,42.31,hold,2.84,2532,107131.76,7131.76
252,2016-03-04,42.42,hold,2.84,2532,107410.28,7410.28
253,2016-03-07,42.16,buy,2.84,2532,106751.96,6751.96
254,2016-03-08,41.90,hold,2.84,2532,106093.64,6093.64
255,2016-03-09,42.26,buy,2.84,2532,107005.16,7005.16
256,2016-03-10,42.22,buy,2.84,2532,106903.88,6903.88
257,2016-03-11,42.87,buy,2.84,2532,108549.68,8549.68
258,2016-03-14,42.92,buy,2.84,2532,108676.28,8676.28
259,2016-03-15,43.08,buy,2.84,2532,109081.40,9081.40
260,2016-03-16,43.58,buy,2.84,2532,110347.40,10347.40
261,2016-03-17,43.74,hold,2.84,2532,110752.52,10752.52
262,2016-03-18,43.59,hold,2.84,2532,110372.72,10372.72
263,2016-03-21,43.74,hold,2.84,2532,110752.52,10752.52
264,2016-03-22,43.75,hold,2.84,2532,110777.84,10777.84
265,2016-03-23,43.50,hold,2.84,2532,110144.84,10144.84
266,2016-03-24,43.62,hold,2.84,2532,110448.68,10448.68
267,2016-03-28,43.51,buy,2.84,2532,110170.16,10170.16
268,2016-03-29,44.19,hold,2.84,2532,111891.92,11891.92
269,2016-03-30,44.45,hold,2.84,2532,112550.24,12550.24
270,2016-03-31,44.36,hold,2.84,2532,112322.36,12322.36
271,2016-04-01,44.70,hold,2.84,2532,113183.24,13183.24
272,2016-04-04,44.53,buy,2.84,2532,112752.80,12752.80
273,2016-04-05,44.10,sell,111664.04,0,111664.04,11664.04
274,2016-04-06,44.53,hold,111664.04,0,111664.04,11664.04
275,2016-04-07,43.89,sell,111664.04,0,111664.04,11664.04
276,2016-04-08,43.89,hold,111664.04,0,111664.04,11664.04
277,2016-04-11,43.77,hold,111664.04,0,111664.04,11664.04
278,2016-04-12,44.07,hold,111664.04,0,111664.04,11664.04
279,2016-04-13,44.52,hold,111664.04,0,111664.04,11664.04
280,2016-04-14,44.51,hold,111664.04,0,111664.04,11664.04
281,2016-04-15,44.34,hold,111664.04,0,111664.04,11664.04
282,2016-04-18,44.53,hold,111664.04,0,111664.04,11664.04
283,2016-04-19,44.28,sell,111664.04,0,111664.04,11664.04
284,2016-04-20,44.37,hold,111664.04,0,111664.04,11664.04
285,2016-04-21,44.21,hold,111664.04,0,111664.04,11664.04
286,2016-04-22,43.44,sell,111664.04,0,111664.04,11664.04
287,2016-04-25,43.45,hold,111664.04,0,111664.04,11664.04
288,2016-04-26,43.24,hold,111664.04,0,111664.04,11664.04
289,2016-04-27,43.04,hold,111664.04,0,111664.04,11664.04
290,2016-04-28,42.50,hold,111664.04,0,111664.04,11664.04
291,2016-04-29,42.13,hold,111664.04,0,111664.04,11664.04
292,2016-05-02,42.44,hold,111664.04,0,111664.04,11664.04
293,2016-05-03,42.05,hold,111664.04,0,111664.04,11664.04
294,2016-05-04,41.92,hold,111664.04,0,111664.04,11664.04
295,2016-05-05,41.94,buy,19.76,2662,111664.04,11664.04
296,2016-05-06,42.25,hold,19.76,2662,112489.26,12489.26
297,2016-05-09,42.25,hold,19.76,2662,112489.26,12489.26
298,2016-05-10,42.80,hold,19.76,2662,113953.36,13953.36
299,2016-05-11,42.49,hold,19.76,2662,113128.14,13128.14
300,2016-05-12,42.37,hold,19.76,2662,112808.70,12808.70
301,2016-05-13,42.21,hold,19.76,2662,112382.78,12382.78
302,2016-05-16,42.80,hold,19.76,2662,113953.36,13953.36
303,2016-05-17,42.37,hold,19.76,2662,112808.70,12808.70
304,2016-05-18,42.45,hold,19.76,2662,113021.66,13021.66
305,2016-05-19,42.22,hold,19.76,2662,112409.40,12409.40
306,2016-05-20,42.73,hold,19.76,2662,113767.02,13767.02
307,2016-05-23,42.65,hold,19.76,2662,113554.06,13554.06
308,2016-05-24,43.45,hold,19.76,2662,115683.66,15683.66
309,2016-05-25,43.75,hold,19.76,2662,116482.26,16482.26
310,2016-05-26,43.89,hold,19.76,2662,116854.94,16854.94
311,2016-05-27,44.10,hold,19.76,2662,117413.96,17413.96
312,2016-05-31,44.19,hold,19.76,2662,117653.54,17653.54
313,2016-06-01,44.08,hold,19.76,2662,117360.72,17360.72
314,2016-06-02,44.04,hold,19.76,2662,117254.24,17254.24
315,2016-06-03,43.94,hold,19.76,2662,116988.04,16988.04
316,2016-06-06,44.02,hold,19.76,2662,117201.00,17201.00
317,2016-06-07,44.20,hold,19.76,2662,117680.16,17680.16
318,2016-06-08,44.29,hold,19.76,2662,117919.74,17919.74
319,2016-06-09,44.30,hold,19.76,2662,117946.36,17946.36
320,2016-06-10,43.96,hold,19.76,2662,117041.28,17041.28
321,2016-06-13,43.47,hold,19.76,2662,115736.90,15736.90
322,2016-06-14,43.57,hold,19.76,2662,116003.10,16003.10
323,2016-06-15,43.46,hold,19.76,2662,115710.28,15710.28
324,2016-06-16,43.55,hold,19.76,2662,115949.86,15949.86
325,2016-06-17,43.05,hold,19.76,2662,114618.86,14618.86
326,2016-06-20,43.23,hold,19.76,2662,115098.02,15098.02
327,2016-06-21,43.53,hold,19.76,2662,115896.62,15896.62
328,2016-06-22,43.38,hold,19.76,2662,115497.32,15497.32
329,2016-06-23,43.97,hold,19.76,2662,117067.90,17067.90
330,2016-06-24,42.28,hold,19.76,2662,112569.12,12569.12
331,2016-06-27,41.43,hold,19.76,2662,110306.42,10306.42
332,2016-06-28,42.25,buy,19.76,2662,112489.26,12489.26
333,2016-06-29,42.90,hold,19.76,2662,114219.56,14219.56
334,2016-06-30,43.37,hold,19.76,2662,115470.70,15470.70
335,2016-07-01,43.47,hold,19.76,2662,115736.90,15736.90
336,2016-07-05,43.15,hold,19.76,2662,114885.06,14885.06
337,2016-07-06,43.45,buy,19.76,2662,115683.66,15683.66
338,2016-07-07,43.45,buy,19.76,2662,115683.66,15683.66
339,2016-07-08,44.13,hold,19.76,2662,117493.82,17493.82
340,2016-07-11,44.39,buy,19.76,2662,118185.94,18185.94
341,2016-07-12,44.75,buy,19.76,2662,119144.26,19144.26
342,2016-07-13,44.76,hold,19.76,2662,119170.88,19170.88
343,2016-07-14,45.05,buy,19.76,2662,119942.86,19942.86
344,2016-07-15,45.01,hold,19.76,2662,119836.38,19836.38
345,2016-07-18,45.31,hold,19.76,2662,120634.98,20634.98
346,2016-07-19,45.21,hold,19.76,2662,120368.78,20368.78
347,2016-07-20,45.80,buy,19.76,2662,121939.36,21939.36
348,2016-07-21,45.56,hold,19.76,2662,121300.48,21300.48
349,2016-07-22,45.83,hold,19.76,2662,122019.22,22019.22
350,2016-07-25,45.77,hold,19.76,2662,121859.50,21859.50
351,2016-07-26,45.87,buy,19.76,2662,122125.70,22125.70
352,2016-07-27,46.25,hold,19.76,2662,123137.26,23137.26
353,2016-07-28,46.28,hold,19.76,2662,123217.12,23217.12
354,2016-07-29,46.45,hold,19.76,2662,123669.66,23669.66
355,2016-08-01,46.54,hold,19.76,2662,123909.24,23909.24
356,2016-08-02,46.19,hold,19.76,2662,122977.54,22977.54
357,2016-08-03,46.35,hold,19.76,2662,123403.46,23403.46
358,2016-08-04,46.60,hold,19.76,2662,124068.96,24068.96
359,2016-08-05,47.05,hold,19.76,2662,125266.86,25266.86
360,2016-08-08,47.04,hold,19.76,2662,125240.24,25240.24
361,2016-08-09,47.14,hold,19.76,2662,125506.44,25506.44
362,2016-08-10,46.99,hold,19.76,2662,125107.14,25107.14
363,2016-08-11,47.16,hold,19.76,2662,125559.68,25559.68
364,2016-08-12,47.11,hold,19.76,2662,125426.58,25426.58

In [ ]:
dataframe = dataframe.rename(columns={'adjusted_close': 'price'})

In [ ]:
dataframe['directive'] = dataframe.apply(custom_argmax, axis=1)
dataframe[['pmapsell', 'pmapbuy', 'pmaphold']] = dataframe.apply(custom_argmax2, axis=1)

stock_names = dataframe['name'].unique()
result_dict = dict()
for stock_name in stock_names:

    search_df = dataframe.loc[dataframe['name'] == stock_name]

    buysell = BuySell(capital=initial_capital)

    # result_dict[stock_name] = buysell.buyandhold(dataframe=search_df)
    result_dict[stock_name] = buysell.process(dataframe=search_df)['profit'].iloc[-1]

print(result_dict)

In [6]:
pd.DataFrame(result_dict, columns=result_dict.keys(), index=[0])

,xlp,xlu,xlv,xly,dia,ewa,ewc,ewg,ewh,ewj,eww,spy,xlb,xle,xlf,xli,xlk
0,-952.84,-521.72,-1193.9,-1832.65,-1837.33,-1886.12,-2597.59,-2662.01,-2874.96,-1074.24,-3837.58,-1075.86,-2023.5,-3582.12,-1830.28,-818.84,-1408.09

In [37]:
pd.read_csv('../dataset/finance/stocks/stocks.csv')['name'].unique()

array(['dia', 'ewa', 'ewc', 'ewg', 'ewh', 'ewj', 'eww', 'spy', 'xlb',
       'xle', 'xlf', 'xli', 'xlk', 'xlp', 'xlu', 'xlv', 'xly'],
      dtype=object)