In [26]:
import pandas as pd
import numpy as np
pd.options.display.max_rows = 999

In [3]:
class BuySell:

    def __init__(self, capital):
        self.initial_capital = capital
        self.current_capital = capital
        self.share_amount = 0


    def buyandhold(self, dataframe):
        """

        Args:
            dataframe: (pd.DataFrame) should contains price and directive, date columns

        Returns: (float) profit

        """
        first_price = dataframe.iloc[0].loc['price']
        last_price  = dataframe.iloc[-1].loc['price']

        self.current_capital, self.share_amount = BuySell._buy(self.initial_capital, first_price)
        money, self.share_amount = BuySell._sell(self.share_amount, last_price)
        self.current_capital += money

        profit = self.current_capital - self.initial_capital

        return profit

    @staticmethod
    def _buy(money, price):
        """buys if appliable
        Returns: (float, int) current_money, share_amount"""

        remaining_money = money
        share_amount = 0

        if money > price:
            share_amount = int(money / price)
            remaining_money = money - share_amount * price

        return remaining_money, share_amount

    @staticmethod
    def _sell(share_amount, price):
        """sells all shares :)
        Returns: (float, int) current_money, share_amount"""
        money = share_amount * price
        return money, 0



    def process(self, dataframe):
        """

        Args:
            dataframe: (pd.DataFrame) should contains price and directive, date columns

        Returns: (float) profit

        """
        capital_list = list()
        share_amount_list = list()

        for idx,row in dataframe.iterrows():
            if row['directive'] == 'buy':
                remaining_money, share_amount = BuySell._buy(self.current_capital, row['price'])
                self.current_capital = remaining_money
                self.share_amount += share_amount

            if row['directive'] == 'sell':
                money, share_amount = BuySell._sell(self.share_amount, row['price'])
                self.current_capital += money
                self.share_amount = share_amount
            capital_list.append(self.current_capital)
            share_amount_list.append(self.share_amount)

        dataframe.loc[:,'current_capital'] = capital_list
        dataframe.loc[:,'share_amount'] = share_amount_list
        dataframe.loc[:,'total_capital'] = dataframe['current_capital'] + dataframe['share_amount']*dataframe['price']

        dataframe.loc[:,'profit'] = dataframe['total_capital'] - self.initial_capital


        return dataframe

In [32]:
def label_to_directives(row):
    row = row[['label_buy','label_sell','label_hold']]
    argmax_idx = np.argmax(row.values)

    if argmax_idx == 0:
        return 'buy'
    if argmax_idx == 1:
        return 'sell'
    return 'hold'

def custom_argmax2(row):
    row = row[['psell','pbuy','phold']]

    argmax_idx = np.argmax(row.values)


    if argmax_idx == 0:
        return pd.Series([1,0,0])
    if argmax_idx == 1:
        return pd.Series([0,1,0])
    return pd.Series([0,0,1])

In [33]:
np.random.seed(42)
initial_capital = 100000
# size = 100
# fake_dataframe = pd.DataFrame({'price':np.random.randint(100,150, size=size),
#                                'directive':np.random.choice(['buy','hold','sell'], size=size, replace=True),
#      'name':np.random.choice(['xlp','xlu','xlv','xly','dia','ewa','ewc','ewg','ewh','ewj','eww','spy','xlb','xle','xlf','xli','xlk'], size=size, replace=True)})

In [34]:
                          
dataframe = pd.read_csv('../dataset/finance/stocks/indicator_dataset.csv')

dataframe = dataframe.loc[dataframe['name'] == 'dia']

In [35]:
dataframe['directive'] = dataframe.apply(label_to_directives, axis=1)

In [36]:
dataframe['price'] = dataframe['raw_adjusted_close'].values
dataframe.head()

,date,name,label_buy,label_sell,label_hold,raw_adjusted_close,open,high,low,close,...,kddiff_14,kddiff_18,kddiff_22,year,month,week,weekday,day,directive,price
0,2000-02-29,dia,0.0,0.0,1.0,101.56,-0.710673,-0.704031,-0.709038,-0.697910,...,0.473748,0.411291,0.476011,-1.632201,-1.315545,-1.168300,-0.728940,1.518422,hold,101.56
17,2000-03-01,dia,0.0,0.0,1.0,101.62,-0.710673,-0.681081,-0.700372,-0.695828,...,1.058784,0.877728,0.939842,-1.632201,-1.023080,-1.168300,-0.014760,-1.676586,hold,101.62
34,2000-03-02,dia,0.0,0.0,1.0,101.69,-0.710673,-0.699510,-0.689626,-0.693398,...,0.945625,0.742905,0.754959,-1.632201,-1.023080,-1.168300,0.699420,-1.562479,hold,101.69
51,2000-03-03,dia,0.0,0.0,1.0,103.88,-0.710673,-0.619533,-0.620299,-0.617391,...,1.008195,0.788032,0.749832,-1.632201,-1.023080,-1.168300,1.413601,-1.448371,hold,103.88
68,2000-03-06,dia,0.0,0.0,1.0,101.72,-0.710673,-0.639353,-0.684773,-0.692357,...,0.398814,0.429081,0.315519,-1.632201,-1.023080,-1.101326,-1.443121,-1.106049,hold,101.72

In [39]:
buysell = BuySell(capital=initial_capital)
result_df = buysell.process(dataframe.iloc[:200])

C:\Users\ugurg\Anaconda3\lib\site-packages\pandas\core\indexing.py:537: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

In [40]:
subset = ['date','price','directive','current_capital','share_amount','total_capital', 'profit']
result_df[subset]

,date,price,directive,current_capital,share_amount,total_capital,profit
0,2000-02-29,101.56,hold,100000.00,0,100000.00,0.00
17,2000-03-01,101.62,hold,100000.00,0,100000.00,0.00
34,2000-03-02,101.69,hold,100000.00,0,100000.00,0.00
51,2000-03-03,103.88,hold,100000.00,0,100000.00,0.00
68,2000-03-06,101.72,hold,100000.00,0,100000.00,0.00
85,2000-03-07,98.00,buy,40.00,1020,100000.00,0.00
102,2000-03-08,98.47,buy,40.00,1020,100479.40,479.40
119,2000-03-09,100.33,hold,40.00,1020,102376.60,2376.60
136,2000-03-10,99.56,hold,40.00,1020,101591.20,1591.20
153,2000-03-13,99.62,hold,40.00,1020,101652.40,1652.40
170,2000-03-14,98.47,buy,40.00,1020,100479.40,479.40
187,2000-03-15,101.62,buy,40.00,1020,103692.40,3692.40
204,2000-03-16,106.78,hold,40.00,1020,108955.60,8955.60
221,2000-03-17,106.12,hold,40.00,1020,108282.40,8282.40
238,2000-03-20,106.81,hold,40.00,1020,108986.20,8986.20
255,2000-03-21,109.12,hold,40.00,1020,111342.40,11342.40
272,2000-03-22,108.58,hold,40.00,1020,110791.60,10791.60
289,2000-03-23,111.12,hold,40.00,1020,113382.40,13382.40
306,2000-03-24,111.12,hold,40.00,1020,113382.40,13382.40
323,2000-03-27,109.81,hold,40.00,1020,112046.20,12046.20
340,2000-03-28,109.38,hold,40.00,1020,111607.60,11607.60
357,2000-03-29,110.72,hold,40.00,1020,112974.40,12974.40
374,2000-03-30,110.06,hold,40.00,1020,112301.20,12301.20
391,2000-03-31,109.44,hold,40.00,1020,111668.80,11668.80
408,2000-04-03,112.69,hold,40.00,1020,114983.80,14983.80
425,2000-04-04,111.69,hold,40.00,1020,113963.80,13963.80
442,2000-04-05,110.38,hold,40.00,1020,112627.60,12627.60
459,2000-04-06,111.42,hold,40.00,1020,113688.40,13688.40
476,2000-04-07,110.91,hold,40.00,1020,113168.20,13168.20
493,2000-04-10,112.06,hold,40.00,1020,114341.20,14341.20
510,2000-04-11,113.25,sell,115555.00,0,115555.00,15555.00
527,2000-04-12,110.52,hold,115555.00,0,115555.00,15555.00
544,2000-04-13,109.03,hold,115555.00,0,115555.00,15555.00
561,2000-04-14,102.52,buy,14.96,1127,115555.00,15555.00
578,2000-04-17,106.03,hold,14.96,1127,119510.77,19510.77
595,2000-04-18,107.78,hold,14.96,1127,121483.02,21483.02
612,2000-04-19,106.81,hold,14.96,1127,120389.83,20389.83
629,2000-04-20,108.78,hold,14.96,1127,122610.02,22610.02
646,2000-04-24,108.88,hold,14.96,1127,122722.72,22722.72
663,2000-04-25,111.53,sell,125709.27,0,125709.27,25709.27
680,2000-04-26,109.47,sell,125709.27,0,125709.27,25709.27
697,2000-04-27,108.38,hold,125709.27,0,125709.27,25709.27
714,2000-04-28,107.56,hold,125709.27,0,125709.27,25709.27
731,2000-05-01,108.12,hold,125709.27,0,125709.27,25709.27
748,2000-05-02,107.06,hold,125709.27,0,125709.27,25709.27
765,2000-05-03,104.81,hold,125709.27,0,125709.27,25709.27
782,2000-05-04,104.31,hold,125709.27,0,125709.27,25709.27
799,2000-05-05,105.84,hold,125709.27,0,125709.27,25709.27
816,2000-05-08,105.83,hold,125709.27,0,125709.27,25709.27
833,2000-05-09,105.38,hold,125709.27,0,125709.27,25709.27
850,2000-05-10,103.31,hold,125709.27,0,125709.27,25709.27
867,2000-05-11,105.75,hold,125709.27,0,125709.27,25709.27
884,2000-05-12,106.25,hold,125709.27,0,125709.27,25709.27
901,2000-05-15,108.20,hold,125709.27,0,125709.27,25709.27
918,2000-05-16,109.31,sell,125709.27,0,125709.27,25709.27
935,2000-05-17,107.75,hold,125709.27,0,125709.27,25709.27
952,2000-05-18,107.44,hold,125709.27,0,125709.27,25709.27
969,2000-05-19,106.56,hold,125709.27,0,125709.27,25709.27
986,2000-05-22,105.53,hold,125709.27,0,125709.27,25709.27
1003,2000-05-23,104.44,hold,125709.27,0,125709.27,25709.27
1020,2000-05-24,105.44,hold,125709.27,0,125709.27,25709.27
1037,2000-05-25,103.50,hold,125709.27,0,125709.27,25709.27
1054,2000-05-26,103.12,buy,5.99,1219,125709.27,25709.27
1071,2000-05-30,105.44,hold,5.99,1219,128537.35,28537.35
1088,2000-05-31,105.31,hold,5.99,1219,128378.88,28378.88
1105,2000-06-01,106.50,hold,5.99,1219,129829.49,29829.49
1122,2000-06-02,107.52,hold,5.99,1219,131072.87,31072.87
1139,2000-06-05,108.25,hold,5.99,1219,131962.74,31962.74
1156,2000-06-06,107.64,hold,5.99,1219,131219.15,31219.15
1173,2000-06-07,108.34,sell,132072.45,0,132072.45,32072.45
1190,2000-06-08,106.78,hold,132072.45,0,132072.45,32072.45
1207,2000-06-09,106.27,hold,132072.45,0,132072.45,32072.45
1224,2000-06-12,105.72,hold,132072.45,0,132072.45,32072.45
1241,2000-06-13,106.56,hold,132072.45,0,132072.45,32072.45
1258,2000-06-14,107.25,hold,132072.45,0,132072.45,32072.45
1275,2000-06-15,106.84,hold,132072.45,0,132072.45,32072.45
1292,2000-06-16,104.52,hold,132072.45,0,132072.45,32072.45
1309,2000-06-19,105.59,hold,132072.45,0,132072.45,32072.45
1326,2000-06-20,104.75,hold,132072.45,0,132072.45,32072.45
1343,2000-06-21,104.94,hold,132072.45,0,132072.45,32072.45
1360,2000-06-22,104.00,buy,96.45,1269,132072.45,32072.45
1377,2000-06-23,104.44,hold,96.45,1269,132630.81,32630.81
1394,2000-06-26,105.97,hold,96.45,1269,134572.38,34572.38
1411,2000-06-27,105.38,hold,96.45,1269,133823.67,33823.67
1428,2000-06-28,105.38,hold,96.45,1269,133823.67,33823.67
1445,2000-06-29,104.25,buy,96.45,1269,132389.70,32389.70
1462,2000-06-30,104.38,buy,96.45,1269,132554.67,32554.67
1479,2000-07-03,105.97,hold,96.45,1269,134572.38,34572.38
1496,2000-07-05,105.00,buy,96.45,1269,133341.45,33341.45
1513,2000-07-06,105.09,hold,96.45,1269,133455.66,33455.66
1530,2000-07-07,106.33,hold,96.45,1269,135029.22,35029.22
1547,2000-07-10,106.50,hold,96.45,1269,135244.95,35244.95
1564,2000-07-11,107.25,hold,96.45,1269,136196.70,36196.70
1581,2000-07-12,107.81,hold,96.45,1269,136907.34,36907.34
1598,2000-07-13,108.00,hold,96.45,1269,137148.45,37148.45
1615,2000-07-14,108.06,hold,96.45,1269,137224.59,37224.59
1632,2000-07-17,108.00,hold,96.45,1269,137148.45,37148.45
1649,2000-07-18,107.62,hold,96.45,1269,136666.23,36666.23
1666,2000-07-19,107.19,hold,96.45,1269,136120.56,36120.56
1683,2000-07-20,109.09,hold,96.45,1269,138531.66,38531.66
1700,2000-07-21,107.00,hold,96.45,1269,135879.45,35879.45
1717,2000-07-24,106.81,hold,96.45,1269,135638.34,35638.34
1734,2000-07-25,106.78,hold,96.45,1269,135600.27,35600.27
1751,2000-07-26,105.50,hold,96.45,1269,133975.95,33975.95
1768,2000-07-27,106.03,hold,96.45,1269,134648.52,34648.52
1785,2000-07-28,105.00,buy,96.45,1269,133341.45,33341.45
1802,2000-07-31,105.00,buy,96.45,1269,133341.45,33341.45
1819,2000-08-01,106.00,buy,96.45,1269,134610.45,34610.45
1836,2000-08-02,107.00,hold,96.45,1269,135879.45,35879.45
1853,2000-08-03,106.94,buy,96.45,1269,135803.31,35803.31
1870,2000-08-04,107.50,buy,96.45,1269,136513.95,36513.95
1887,2000-08-07,108.62,buy,96.45,1269,137935.23,37935.23
1904,2000-08-08,109.66,hold,96.45,1269,139254.99,39254.99
1921,2000-08-09,109.12,hold,96.45,1269,138569.73,38569.73
1938,2000-08-10,109.22,hold,96.45,1269,138696.63,38696.63
1955,2000-08-11,110.34,hold,96.45,1269,140117.91,40117.91
1972,2000-08-14,111.72,hold,96.45,1269,141869.13,41869.13
1989,2000-08-15,110.94,hold,96.45,1269,140879.31,40879.31
2006,2000-08-16,111.06,hold,96.45,1269,141031.59,41031.59
2023,2000-08-17,110.84,hold,96.45,1269,140752.41,40752.41
2040,2000-08-18,110.44,hold,96.45,1269,140244.81,40244.81
2057,2000-08-21,110.91,hold,96.45,1269,140841.24,40841.24
2074,2000-08-22,111.55,hold,96.45,1269,141653.40,41653.40
2091,2000-08-23,111.50,hold,96.45,1269,141589.95,41589.95
2108,2000-08-24,112.03,hold,96.45,1269,142262.52,42262.52
2125,2000-08-25,112.23,hold,96.45,1269,142516.32,42516.32
2142,2000-08-28,112.69,hold,96.45,1269,143100.06,43100.06
2159,2000-08-29,112.53,hold,96.45,1269,142897.02,42897.02
2176,2000-08-30,111.16,hold,96.45,1269,141158.49,41158.49
2193,2000-08-31,112.47,hold,96.45,1269,142820.88,42820.88
2210,2000-09-01,112.53,hold,96.45,1269,142897.02,42897.02
2227,2000-09-05,112.86,hold,96.45,1269,143315.79,43315.79
2244,2000-09-06,113.19,sell,143734.56,0,143734.56,43734.56
2261,2000-09-07,112.78,hold,143734.56,0,143734.56,43734.56
2278,2000-09-08,112.09,hold,143734.56,0,143734.56,43734.56
2295,2000-09-11,112.12,hold,143734.56,0,143734.56,43734.56
2312,2000-09-12,112.91,sell,143734.56,0,143734.56,43734.56
2329,2000-09-13,112.06,sell,143734.56,0,143734.56,43734.56
2346,2000-09-14,111.02,sell,143734.56,0,143734.56,43734.56
2363,2000-09-15,109.00,sell,143734.56,0,143734.56,43734.56
2380,2000-09-18,108.25,hold,143734.56,0,143734.56,43734.56
2397,2000-09-19,107.97,hold,143734.56,0,143734.56,43734.56
2414,2000-09-20,106.94,hold,143734.56,0,143734.56,43734.56
2431,2000-09-21,107.69,hold,143734.56,0,143734.56,43734.56
2448,2000-09-22,108.75,hold,143734.56,0,143734.56,43734.56
2465,2000-09-25,108.09,hold,143734.56,0,143734.56,43734.56
2482,2000-09-26,106.16,hold,143734.56,0,143734.56,43734.56
2499,2000-09-27,106.52,hold,143734.56,0,143734.56,43734.56
2516,2000-09-28,108.34,hold,143734.56,0,143734.56,43734.56
2533,2000-09-29,106.62,hold,143734.56,0,143734.56,43734.56
2550,2000-10-02,107.09,hold,143734.56,0,143734.56,43734.56
2567,2000-10-03,107.03,hold,143734.56,0,143734.56,43734.56
2584,2000-10-04,107.89,hold,143734.56,0,143734.56,43734.56
2601,2000-10-05,107.47,hold,143734.56,0,143734.56,43734.56
2618,2000-10-06,106.19,hold,143734.56,0,143734.56,43734.56
2635,2000-10-09,105.80,hold,143734.56,0,143734.56,43734.56
2652,2000-10-10,104.91,hold,143734.56,0,143734.56,43734.56
2669,2000-10-11,104.41,hold,143734.56,0,143734.56,43734.56
2686,2000-10-12,100.38,hold,143734.56,0,143734.56,43734.56
2703,2000-10-13,101.88,hold,143734.56,0,143734.56,43734.56
2720,2000-10-16,102.70,hold,143734.56,0,143734.56,43734.56
2737,2000-10-17,100.59,hold,143734.56,0,143734.56,43734.56
2754,2000-10-18,99.78,buy,51.36,1440,143734.56,43734.56
2771,2000-10-19,101.84,buy,51.36,1440,146700.96,46700.96
2788,2000-10-20,102.38,buy,51.36,1440,147478.56,47478.56
2805,2000-10-23,103.14,hold,51.36,1440,148572.96,48572.96
2822,2000-10-24,103.44,hold,51.36,1440,149004.96,49004.96
2839,2000-10-25,102.89,buy,51.36,1440,148212.96,48212.96
2856,2000-10-26,103.69,buy,51.36,1440,149364.96,49364.96
2873,2000-10-27,106.19,hold,51.36,1440,152964.96,52964.96
2890,2000-10-30,108.19,hold,51.36,1440,155844.96,55844.96
2907,2000-10-31,109.41,hold,51.36,1440,157601.76,57601.76
2924,2000-11-01,109.16,hold,51.36,1440,157241.76,57241.76
2941,2000-11-02,108.64,hold,51.36,1440,156492.96,56492.96
2958,2000-11-03,108.22,hold,51.36,1440,155888.16,55888.16
2975,2000-11-06,110.03,sell,158494.56,0,158494.56,58494.56
2992,2000-11-07,109.75,sell,158494.56,0,158494.56,58494.56
3009,2000-11-08,108.75,hold,158494.56,0,158494.56,58494.56
3026,2000-11-09,108.22,hold,158494.56,0,158494.56,58494.56
3043,2000-11-10,106.12,hold,158494.56,0,158494.56,58494.56
3060,2000-11-13,105.44,hold,158494.56,0,158494.56,58494.56
3077,2000-11-14,107.31,hold,158494.56,0,158494.56,58494.56
3094,2000-11-15,107.31,hold,158494.56,0,158494.56,58494.56
3111,2000-11-16,106.62,hold,158494.56,0,158494.56,58494.56
3128,2000-11-17,106.23,hold,158494.56,0,158494.56,58494.56
3145,2000-11-20,104.69,hold,158494.56,0,158494.56,58494.56
3162,2000-11-21,105.38,hold,158494.56,0,158494.56,58494.56
3179,2000-11-22,103.88,hold,158494.56,0,158494.56,58494.56
3196,2000-11-24,105.06,hold,158494.56,0,158494.56,58494.56
3213,2000-11-27,105.88,hold,158494.56,0,158494.56,58494.56
3230,2000-11-28,105.28,hold,158494.56,0,158494.56,58494.56
3247,2000-11-29,105.97,hold,158494.56,0,158494.56,58494.56
3264,2000-11-30,104.41,hold,158494.56,0,158494.56,58494.56
3281,2000-12-01,103.81,hold,158494.56,0,158494.56,58494.56
3298,2000-12-04,106.00,hold,158494.56,0,158494.56,58494.56
3315,2000-12-05,108.94,hold,158494.56,0,158494.56,58494.56
3332,2000-12-06,106.72,hold,158494.56,0,158494.56,58494.56
3349,2000-12-07,105.98,hold,158494.56,0,158494.56,58494.56
3366,2000-12-08,105.00,hold,158494.56,0,158494.56,58494.56
3383,2000-12-11,107.59,hold,158494.56,0,158494.56,58494.56

In [ ]:
dataframe = dataframe.rename(columns={'adjusted_close': 'price'})

In [ ]:
dataframe['directive'] = dataframe.apply(custom_argmax, axis=1)
dataframe[['pmapsell', 'pmapbuy', 'pmaphold']] = dataframe.apply(custom_argmax2, axis=1)

stock_names = dataframe['name'].unique()
result_dict = dict()
for stock_name in stock_names:

    search_df = dataframe.loc[dataframe['name'] == stock_name]

    buysell = BuySell(capital=initial_capital)

    # result_dict[stock_name] = buysell.buyandhold(dataframe=search_df)
    result_dict[stock_name] = buysell.process(dataframe=search_df)['profit'].iloc[-1]

print(result_dict)

In [6]:
pd.DataFrame(result_dict, columns=result_dict.keys(), index=[0])

,xlp,xlu,xlv,xly,dia,ewa,ewc,ewg,ewh,ewj,eww,spy,xlb,xle,xlf,xli,xlk
0,-952.84,-521.72,-1193.9,-1832.65,-1837.33,-1886.12,-2597.59,-2662.01,-2874.96,-1074.24,-3837.58,-1075.86,-2023.5,-3582.12,-1830.28,-818.84,-1408.09

In [7]:
pd.read_csv('../dataset/finance/stocks/stocks.csv').describe()

,open,high,low,close,volume,adjusted_close
count,72861.000000,72861.000000,72861.000000,72861.000000,7.286100e+04,72861.000000
mean,43.596939,43.955792,43.319051,43.651035,1.072731e+07,43.651035
std,36.753077,36.887397,36.492535,36.701361,3.123368e+07,36.701361
min,0.000000,6.450000,5.880000,6.180000,1.000000e+02,6.180000
25%,22.660000,22.830000,22.420000,22.630000,5.360000e+05,22.630000
50%,30.330000,30.540000,30.100000,30.320000,2.545059e+06,30.320000
75%,48.760000,49.090000,48.440000,48.760000,7.694930e+06,48.760000
max,227.410000,228.340000,227.000000,227.760000,8.141804e+08,227.760000