In [1]:
import pandas as pd
import pickle

In [10]:
operations = pd.read_pickle("../input/result/buy_sell_model_regr_2017_09_29 22_35_56_516683")

In [11]:
shares = pd.read_pickle("../input/result/buy_sell_model_regr_shares_2017_09_29 22_35_56_516683")

In [12]:
predictions = pd.read_pickle("../input/result/predictions_model_regr_100epoch_qratio_0_2017_09_29 18_15_07_381385")

In [13]:
operations.head()

   Amounts  Capitals       Dates Names Operations  Prices  Transaction Costs
0    205.0     48.40  2015-03-25   xlb        buy   48.52                  5
1      2.0      0.02  2015-03-26   ewh        buy   21.69                  5
2    205.0   9964.17  2015-03-26   xlb       sell   48.63                  5
3    136.0     25.73  2015-03-27   xlv        buy   73.04                  5
4    136.0   9880.73  2015-03-31   xlv       sell   72.50                  5

In [14]:
shares.head()

,dia,ewa,ewc,ewg,ewh,ewj,eww,spy,xlb,xle,xlf,xli,xlk,xlp,xlu,xlv,xly
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,205.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,205.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,136.0,0.0
4,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [16]:
predictions

        Actual        Date Name  Prediction
0    -0.807523  2015-03-24  ewa   -0.490002
1    -0.764449  2015-03-24  ewc   -0.528527
2    -0.507665  2015-03-24  ewg   -0.454919
3     0.433544  2015-03-24  ewh   -0.313029
4    -0.229484  2015-03-24  ewj   -0.567168
5    -0.896743  2015-03-24  eww   -0.556362
6    -0.898692  2015-03-24  spy   -0.644224
7    -0.807864  2015-03-24  xlb   -1.047506
8     0.861828  2015-03-24  xle   -0.126553
9    -0.921718  2015-03-24  xlf   -0.585888
10   -0.935487  2015-03-24  xli   -0.696335
11   -0.988370  2015-03-24  xlk   -0.669667
12   -0.241347  2015-03-24  xlp   -0.732554
13   -0.823719  2015-03-24  xlu   -0.654782
14   -0.949170  2015-03-24  xlv   -0.534735
15   -0.925553  2015-03-24  xly   -0.463583
16   -0.243696  2015-03-25  dia   -0.107562
17   -0.746395  2015-03-25  ewa   -0.101283
18   -0.214558  2015-03-25  ewc   -0.370069
19   -0.579714  2015-03-25  ewg    0.117312
20    0.227028  2015-03-25  ewh    0.053281
21   -0.767753  2015-03-25  ewj   -0.369739
22   -0.926005  2015-03-25  eww   -0.147243
23   -0.233740  2015-03-25  spy   -0.147822
24    0.222905  2015-03-25  xlb    0.303703
25   -0.116174  2015-03-25  xle   -0.376818
26   -0.083210  2015-03-25  xlf    0.045038
27   -0.263922  2015-03-25  xli   -0.077655
28    0.072494  2015-03-25  xlk    0.156862
29   -0.406925  2015-03-25  xlp    0.023027
...        ...         ...  ...         ...
7109  0.808626  2016-11-16  ewh    0.417282
7110  0.904782  2016-11-16  ewj    0.711291
7111 -0.655828  2016-11-16  eww   -0.260234
7112  0.473109  2016-11-16  spy    0.206968
7113  0.041324  2016-11-16  xlb    0.095041
7114 -0.586965  2016-11-16  xle   -0.842631
7115  0.879231  2016-11-16  xlf    0.245441
7116  0.209313  2016-11-16  xli    0.218609
7117  0.562814  2016-11-16  xlk    0.050734
7118 -0.175436  2016-11-16  xlp   -0.080826
7119  0.021539  2016-11-16  xlu   -0.235281
7120  0.379119  2016-11-16  xlv    0.143460
7121  0.835255  2016-11-16  xly    0.209906
7122 -0.416740  2016-11-17  dia    0.086344
7123 -0.686647  2016-11-17  ewa   -0.089742
7124  0.156070  2016-11-17  ewc    0.269079
7125 -0.724332  2016-11-17  ewg   -0.006100
7126  0.281873  2016-11-17  ewh    0.224224
7127 -0.904389  2016-11-17  ewj   -0.783425
7128 -0.992702  2016-11-17  eww   -0.303804
7129 -0.220094  2016-11-17  spy    0.034341
7130 -0.143657  2016-11-17  xlb    0.250108
7131  0.387940  2016-11-17  xle   -0.266853
7132  0.000000  2016-11-17  xlf    0.300010
7133 -0.032604  2016-11-17  xli    0.177977
7134 -0.084188  2016-11-17  xlk    0.235585
7135 -0.340952  2016-11-17  xlp   -0.010903
7136 -0.292711  2016-11-17  xlu    0.042549
7137 -0.787412  2016-11-17  xlv   -0.290974
7138 -0.297648  2016-11-17  xly    0.031010

[7139 rows x 4 columns]

In [18]:
sum((predictions.Actual / predictions.Prediction) > 0) / predictions.shape[0]

0.74029976187141056

In [21]:
from sklearn.metrics import confusion_matrix

In [34]:
y_true = predictions.Actual > 0
y_pred = predictions.Prediction > 0
tn, fp, fn, tp = confusion_matrix(y_true, y_pred).ravel()
(tn, fp, fn, tp)

(2539, 985, 839, 2776)

In [25]:
unique_dates = predictions.Date.unique()

In [73]:
max_df = pd.DataFrame(columns=predictions.columns)
# append only positive max samples for any given dates
for date in unique_dates:
    try:
        max_pos_idx = predictions.loc[(predictions.Date == date) & (predictions.Prediction > 0)].Prediction.idxmax()
        max_df = max_df.append(predictions.iloc[max_pos_idx])
    except:
        continue
# append all negative samples
max_df = max_df.append(predictions.loc[predictions.Prediction < 0])

In [75]:
y_true = max_df.Actual > 0
y_pred = max_df.Prediction > 0
tn, fp, fn, tp = confusion_matrix(y_true, y_pred).ravel()
(tn, fp, fn, tp)

(2539, 80, 839, 311)

In [78]:
(311)/(311+80) # max

0.7953964194373402

In [79]:
(2776)/(2776+985) # all

0.7381015687317203

In [80]:
(tn/(tn+fn))

0.75162818235642392